### ISSUE TITLE
「('isident' 参照)」でK →「残念ですが ('isident' にはヘルプがありません」

### ISSUE THREAD

**Issue by tyru** [vim-jp/vimdoc-ja-working#10]
## 現象

タイトルの通り、`('isident' 参照)`の`'isident'`の上で`K`コマンドを実行すると
`E149: 残念ですが ('isident' にはヘルプがありません`と表示されてしまいます。

## 場所

`:help /\i`

## 備考

* 原文では`(see 'isident' option)`となっていて`(`が隣接していないため発生しません。
* `:helpgrep ('\w\+'` で検索すると他にも結構あるようです。
* ちなみに`filetype=help`で'iskeyword'の値は`!-~,^*,^|,^",192-255`でした。

## 修正案

修正すべきとなった場合、どちらが良いでしょうか？

1. `(`の後に半角スペースを入れる (例：`('isident' 参照)`→`( 'isident' 参照)`)
1. `'isident'`を`|`で囲む (例：`('isident' 参照)`→`(|'isident'| 参照)`)
  * ハイライトグループが変わってしまいますが…

**Comment by machakann** [comment]
vim-jp/vimdoc-ja#89
おそらく関連issueです。

**Comment by mattn** [comment]
(see 'xxx') にするのがいいんじゃないですかね。

**Comment by koron** [comment]
重複ですが、このままこちらで作業するために残しましょう。

vimdoc-jaとしては、基本的にスペースを追加する、という対応が良いと思います。

本体の方は `isk` を弄るか…でもそれだと対応しきれない( `foo(` は検索できるままにしたいから)し、
直すにしてもhelp specificになってしまうので、私には良いアイデアが無いです。

**Comment by tyru** [comment]
自分もスペース案に賛成です。
`(see 'xxx')`はやはり英語なのでスペースがいいかなと。

もし反対意見なければ自分が修正進めようと思いますがいいでしょうか。

**Comment by sgur** [comment]
単なるアイデアですが、`(詳細は 'xxx' を参照)` など、`(` と `'` の間に何か追記するのはいかがでしょう？
単にスペースが空いているより自然に見えるように思えます。

**Comment by tyru** [comment]
確かにそちらの方が良さそうですね。
こっちの案で作業して良いでしょうか？

\# Add Reactions だと通知が来ないのが難点だな…

**Comment by h-east** [comment]
> (詳細は 'xxx' を参照) など、( と ' の間に何か追記するのはいかがでしょう？

うーん。
`en`の方を修正(スペースを追加)する場合が多いと思いますし、`ja`も手間を考えるとそのままの方が良いと思います。

**Comment by koron** [comment]
@h-east 英語のほうはそもそも言語特性上 `(see 'foobar')` のように `(` の直後に `'` が来ること自体が少ないんですよね。

**Comment by h-east** [comment]
> 英語のほうはそもそも言語特性上 (see 'foobar') のように ( の直後に ' が来ること自体が少ないんですよね。

```vim
:vimgrep "\W('\w\{2,}" $VIMRUNTIME/doc/*
```
Vim 7.4.1459 で68箇所ありましたよ。

**Comment by koron** [comment]
```
vimdoc-ja-working
$ jvgrep -r "\\W\\('\\w\\w" doc/  | wc -l
110

vim74-kaoriya-win64/vim74/doc
$ jvgrep -r "\\W\\('\\w\\w" *.txt | wc -l
63
```

なんかざっくり見た感じ、単に `('foo')` だけのテキストが結構有りますね

**Comment by koron** [comment]
英語の方も対応するなら、doc 弄るんじゃなくて vim-jp/issues で本体の方に手を入れて、
ft=help の時にだけ機能する単語切り出しロジックを追加しちゃったほうが良さそう。

**Comment by h-east** [comment]
> ft=help の時にだけ機能する単語切り出しロジックを追加しちゃったほうが良さそう。

今、同じこと考えてた:two_men_holding_hands:

**Comment by h-east** [comment]
patch
```patch
diff --git a/src/ex_cmds.c b/src/ex_cmds.c
index 55b0661..ef245a9 100644
--- a/src/ex_cmds.c
+++ b/src/ex_cmds.c
@@ -6114,7 +6114,14 @@ find_help_tags(
 		    || (arg[0] == '\\' && arg[1] == '{'))
 	      *d++ = '\\';
 
-	  for (s = arg; *s; ++s)
+	  /*
+	   * If tag starts with parenthesis, skip it. Fixes CTRL-] on ('option'.
+	   * (would include the facing parenthesis).
+	   */
+	  s = arg;
+	  if ((*s == '(' || *s == ')') && arg[1] != NUL)
+	      s++;
+	  for (; *s; ++s)
 	  {
 	    /*
 	     * Replace "|" with "bar" and '"' with "quote" to match the name of
```

runtime/doc/tags を見たけど、先頭`(`で始まるタグは`(`のみ、先頭`)`で始まるタグは`)`のみだったのでこれでいいんじゃないかな？

**Comment by h-east** [comment]
ちょっと気持ち悪かったので `('` → `'` だけに限定しました。
```patch
diff --git a/src/ex_cmds.c b/src/ex_cmds.c
index 55b0661..594cbc8 100644
--- a/src/ex_cmds.c
+++ b/src/ex_cmds.c
@@ -6114,7 +6114,14 @@ find_help_tags(
 		    || (arg[0] == '\\' && arg[1] == '{'))
 	      *d++ = '\\';
 
-	  for (s = arg; *s; ++s)
+	  /*
+	   * If tag starts with parenthesis, skip it. Fixes CTRL-] on ('option'.
+	   * (would include the facing parenthesis).
+	   */
+	  s = arg;
+	  if (*s == '(' && s[1] == '\'')
+	      s++;
+	  for (; *s; ++s)
 	  {
 	    /*
 	     * Replace "|" with "bar" and '"' with "quote" to match the name of
```

**Comment by h-east** [comment]
何回もごめん。`('shcf')`でも飛べるように修正。
```patch
diff --git a/src/ex_cmds.c b/src/ex_cmds.c
index 55b0661..94814fc 100644
--- a/src/ex_cmds.c
+++ b/src/ex_cmds.c
@@ -6114,6 +6114,12 @@ find_help_tags(
 		    || (arg[0] == '\\' && arg[1] == '{'))
 	      *d++ = '\\';
 
+	  /*
+	   * If tag starts with parenthesis, skip it. Fixes CTRL-] on ('option'.
+	   * (would include the facing parenthesis).
+	   */
+	  if (*arg == '(' && arg[1] == '\'')
+	      arg++;
 	  for (s = arg; *s; ++s)
 	  {
 	    /*
```

**Comment by mattn** [comment]
ちゃんと読んでないので間違ってると思いますが、vim_iswordc(*arg) 見なくても良いですか？

**Comment by h-east** [comment]
@mattn `find_help_tags()`というhelp専用の関数内なので見なくていいと思ってます。

**Comment by h-east** [comment]
patch 7.4.1568 でちゃんと当該のhelpに飛べるようになりました:+1:

後は逆にワークアラウンドで入れたスペースを消せばOKですね。(*.jaxで約12箇所)
*.txtのやつは既にvim_devにpatchを送信済みです。

**Comment by tyru** [comment]
> patch 7.4.1568 でちゃんと当該のhelpに飛べるようになりました:+1:
> 
> 後は逆にワークアラウンドで入れたスペースを消せばOKですね。(*.jaxで約12箇所)
> *.txtのやつは既にvim_devにpatchを送信済みです。

#12 でプルリクエスト出しました。

**Comment by h-east** [comment]
> *.txtのやつは既にvim_devにpatchを送信済みです。

patch 7.4.1604 でついでに修正されてました。(runtime/doc/options.txt)
https://github.com/vim/vim/commit/3848e00e0177abdb31bc600234967863ec487233

**Comment by koron** [comment]
とりあえず vimdoc-ja としてはスペースを入れることで飛べる状態になりました。

Vim本体についても 7.4.1604 で修正され、スペースが無くても飛べるようになりました。
それに伴い #12 でスペースを消すPRが提案されていますが、
あれは少し古いVimを使ってる人たちにとっては逆行する(飛べなくなる)変更ですから、
しばらく期間をおいてからマージすることにしました。
(具体的には7.5のリリースから1ヶ月、もしくは2016/09末の早い方くらいで良いでしょう)

よってこのissueは閉じます。
今後、何か問題が発生した場合は別issueを立ててください。
