### ISSUE TITLE
表記ゆれ: 「同期」「同調」

### ISSUE THREAD

**Issue by Milly** [vim-jp/vimdoc-ja-working#1094]
synchronize の訳として「同期」と「同調」の表記ゆれがある。

`'scrollbind'` については synchronize の訳ではなく、意訳として出現している。

## 現状

```
> rg 同期 | wc -l
53

> rg 同調 | wc -l
10

> rg -l 同期
doc/usr_44.jax
doc/vi_diff.jax
doc/version8.jax
doc/usr_11.jax
doc/usr_08.jax
doc/undo.jax
doc/textprop.jax
doc/terminal.jax
doc/scroll.jax
doc/repeat.jax
doc/recover.jax
doc/quickref.jax
doc/quickfix.jax
doc/popup.jax
doc/os_win32.jax
doc/options.jax
doc/syntax.jax
doc/mbyte.jax
doc/insert.jax
doc/index.jax
doc/if_sniff.jax
doc/gui_w32.jax
doc/fold.jax
doc/diff.jax
doc/develop.jax
doc/channel.jax
doc/builtin.jax

> rg -l 同調
doc/options.jax
```

- 主に「同期」が使われており「同調」は *doc/options.jax* のみで使われている。
- 「同調」は `'scrollbind'`, `'scrollopt'`, `'swapsync'` の説明でのみ使われている。

### 修正案(1)

- 全て「同期」に変更する。
- 表記ゆれ辞書に「同期」を追加する。

### 修正案(2)

- `'swapsync'` の説明を「同期」に変更する。
  - 「ディスクシステムとの同期」の方が一般的な表現である。
  - `'swapsync'` を参照している別のドキュメント内では「同期」が使われている。
- `'scrollbind'`, `'scrollopt'` の説明は変更しない。
  - 「同調」でもおかしくはない。
- `'scrollbind'`, `'scrollopt'` を参照している別のドキュメントの説明を「同調」に変更する。
  - `'scrollbind'`, `'scrollopt'` の説明を「同調」のままにするならば同じ表記にすべき。
  - *doc/scroll.jax* 内、「同期スクロール」を「同調スクロール」に変更する。
  - *doc/quickref.jax* 内、`'scrollbind'` の説明で「同期」を「同調」に変更する。
  - *doc/diff.jax* 内、`view-diffs` の説明で「同期」を「同調」に変更する。
    - ただし `view-diffs` の日本語はあまり適切ではく文全体を書き換えた方がよいと感じる。

**Comment by Milly** [comment]
修正案(1)の利点。

- 変更が少ない。
- 表記ゆれ辞書によりロールバックが防げる。

**Comment by tsuyoshicho** [comment]
同調という語はあってもいいけど、スクロールは同期かなと思う。
ので当座については修正案 1 で対応しておいて、今後どうしても同調が必要になったら

**Comment by h-east** [comment]
修正案(1) に:+1:
