### ISSUE TITLE
'termwinkey'の項目の翻訳間違い

### ISSUE THREAD

**Issue by Dugesia7** [vim-jp/vimdoc-ja-working#1114]
options.jaxの'termwinkey'の項目の1文目ですが、日本語として意味が通らないため何らかの翻訳間違いがあると思われます。

**Comment by h-east** [comment]
Thanks for reporting back!
'termwinkey'の項目全体の見直しをおこないました。
確認をお願いします。

**Comment by Dugesia7** [comment]
修正ありがとうございます。概ね良好です。
ただ一つ、「未設定の場合は CTRL-W が使用される」と「CTRL-W : はコマンドラインに移動する」が「ため、」で接続されるのは違和感があります。
他の解釈があったりはしませんか？

**Comment by h-east** [comment]
@Dugesia7 提案してください。

**Comment by Dugesia7** [comment]
すみません、個々の感覚の問題に過ぎないことを細かく言い過ぎました。
私は英語を読めませんので、他に解釈がないのであればそれが最良だと思います。

**Comment by h-east** [comment]
なるほど。日本語訳 **のみ** を参照して日本語として意味が通らなかったり、違和感がある部分を報告いただいたわけですね。
@Dugesia7 さんのようなパターンの方は初めてだったので、そうとは思わず、

> 違和感があります。
他の解釈があったりはしませんか？

に対して、「うーん、違和感といわれても、`so that`を訳すとこうなるんだけどなぁ。。(原文も参照した上で指摘しているのだろうから)修正案を提案してくれれば良いのに」と思ったのでした。

Pull Requestは出していてmergeする予定ですので、本Issue再オープンしますね。

**Comment by Dugesia7** [comment]
なるほど、了解しました。
mergeが完了したらここを閉じればいい感じですかね？

**Comment by h-east** [comment]
mergeすると自動的にこのIssueはクローズされるようになっています。
(Pull Requestしているブランチのcommitコメントに `Close #1114` 等と書いてあると、merge時に当該Issueが閉じられる仕組み)

**Comment by Dugesia7** [comment]
分かりました。
今回は色々とありがとうございました。
