### ISSUE TITLE
`foo` がハイライト/リンクされない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/vimdoc-ja-working#115]
http://vim-jp.org/vimdoc-ja/repeat.html#packages
例えばこの段落の最後にある ``` `:packadd` ``` がハイライトもリンクもされていません。

**Comment by crazymaster** [comment]
Travis CIに入っているVimが古いからなのでは？

**Comment by k-takata** [comment]
ハイライトがないのは、syntax/help.vim が古いからでしょうね。
html生成スクリプトの中で以下を設定してからTOHtmlを呼べば、ハイライトされるかも？

```vim
syn match helpBacktick	contained "`" conceal
syn match helpCommand		"`[^` \t]\+`"hs=s+1,he=e-1 contains=helpBacktick
syn match helpCommand		"\(^\|[^a-z"[]\)\zs`[^`]\+`\ze\([^a-z\t."']\|$\)"hs=s+1,he=e-1 contains=helpBacktick
hi def link helpCommand		Comment
```

リンクがないのは別途対応が必要そう。

**Comment by k-takata** [comment]
> html生成スクリプトの中で以下を設定してからTOHtmlを呼べば、ハイライトされるかも？

うーむ、ftdetect とか使って読み込ませないといけないのだろうか。

**Comment by k-takata** [comment]
Vim 8.0からhelp.vimを持ってきてみたがダメか…。

**Comment by k-takata** [comment]
ローカルで動かしたらちゃんとリンクしてくれるんだが…。
https://docs.travis-ci.com/user/trusty-ci-environment/
Ubuntu 14.04 を使うか？

**Comment by crazymaster** [comment]
TOHtmlが(も？)新しくする必要があるのでは？

**Comment by k-takata** [comment]
そっちですかね？

**Comment by k-takata** [comment]
Ubuntu 14.04を使うようにしてリンクされるようになりました。
（色が赤というのは微妙な気もするが…いいか。）

**Comment by k-takata** [comment]
> Vim 8.0からhelp.vimを持ってきてみたがダメか…。

'rtp' の設定で `--cmd` を使うべきところ `-c` を使っていたのが原因だった模様。
