### ISSUE TITLE
change.jaxのgPの説明が違う

### ISSUE THREAD

**Issue by garchomp-game** [vim-jp/vimdoc-ja-working#1198]
change.jaxのgPの説明が
"P" と似ているが、カーソルは挿入したテキストの直後に置かれる。
となっていましたが、正しくは
"P" と似ているが、カーソルは挿入したテキストの直前に置かれる。
であることが発覚しました。修正お願いします。

**Comment by tsuyoshicho** [comment]
起動
```
gvim -u NONE
```

version
```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov 17 2022 23:28:36)
MS-Windows 64 ビット GUI 版 with OLE サポート
適用済パッチ: 1-899
Compiled by appveyor@APPVYR-WIN
Huge 版 with GUI.  機能の一覧 有効(+)/無効(-)
```

で確認(正確にはtestのsにカーソルがのっている状態)

![Capture](https://i.gyazo.com/e24d514481d6b927c6128c694b6b7b7e.gif)

見る限りは直後になってると思います...ただ、これだと gp と gP の差がない感じ。
この辺ほかの方にもちょっと聞いてみます。

**Comment by k-takata** [comment]
その例だと、`P` は `s` の前に `abc` が入って、カーソルはその末尾の `c` の位置に来ます。
`gP` は同じように `s` の前に `abc` が入りますが、カーソルはその直後の `s` の位置に来ます。
なので記載は合っていると思います。

**Comment by tsuyoshicho** [comment]
ping @garchomp-game  san

**Comment by k-takata** [comment]
閉じます。
