### ISSUE TITLE
doc/tags-jaに無効なタグが混じっている

### ISSUE THREAD

**Issue by machakann** [vim-jp/vimdoc-ja-working#1206]
`vimdoc-ja/doc/tags-ja` に以下の無効なタグ混じっているようです。これらは文章中で `*` に囲まれていますがヘルプタグとなることを意図されていないもののように思います。

- [`:[vV\x16]`](https://github.com/vim-jp/vimdoc-ja/blob/ca2dac58ec0c02d922a8cd889a340ad4484238ba/doc/tags-ja#L2096)
- [`typecorrect-settings`](https://github.com/vim-jp/vimdoc-ja/blob/ca2dac58ec0c02d922a8cd889a340ad4484238ba/doc/tags-ja#L10022)
- [`typecorrect.txt`](https://github.com/vim-jp/vimdoc-ja/blob/ca2dac58ec0c02d922a8cd889a340ad4484238ba/doc/tags-ja#L10023)

実害というほどではないのですが、手元で `:helptags` してしまうと差分が発生してしまいます。

**Comment by tsuyoshicho** [comment]
そもそもで言うと

* 他のも含めてユーザーがhelptagは生成するべき
* 配布物として常に最新のhelptagを生成して含めるべき

のどっちかやらんといかんのでしょうけど、どうしたもんかな...というはありそう。

**Comment by machakann** [comment]
タグファイルを含めるかに関する議論は #268 のとおりで私としては（それが難しくないかぎり）含めることに異論ありません。ただ、疑問なのは deploy されている tags-ja も Vim が生成したものと思われるのですが、私の手元で生成されるものと差分が出るのは不思議におもっています。Vimのバージョンの問題でしょうか。

すみません、あまり配布用の vimdoc-ja がどのように生成されているのかよくわかっていなくて。おそらく `tools/maketags.vim` かと思ったんですが、特に変わったこともしていないようなのでわからず…

**Comment by tsuyoshicho** [comment]
あ、そっちで論議があったか...なんででしょうね?

**Comment by h-east** [comment]
@machakann 
[9.0.0110](https://github.com/vim/vim/commit/ddab3ce3457aadffb16ce0127f67a99966a065a8) からhelpの例の中のタグを除外するようになりました。

vimdoc-ja-working で使用しているVimは v8.2.0020 ですので、上記バージョン以降のVimの`:helptags`と差分が出ちゃいますね。

**Comment by machakann** [comment]
ありがとうございます。なるほど、たしかに書いていませんでしたが手元の Vim は 9.0.1044 でした。
