### ISSUE TITLE
:h :command-completeの日本語訳について

### ISSUE THREAD

**Issue by koturn** [vim-jp/vimdoc-ja-working#121]
`:h :command-complete` の日本語訳中に「下記の属性を1つ以上指定することで、」とあります。
原文では "by specifying one or the other of the following attributes," が該当すると思うのですが、日本語訳としては「下記の属性のうちいずれか1つを指定することで、」とした方が良いように思われます。

**Comment by crazymaster** [comment]
Thanks!

**Comment by k-takata** [comment]
動作未確認ですが、複数指定できませんでしたか？

**Comment by crazymaster** [comment]
```vim
:command -complete=buffer,file
```
E468: 補完引数はカスタム補完でしか使用できません

できないようです。

**Comment by k-takata** [comment]
すみません。何か別のものと勘違いしていたようです。
