### ISSUE TITLE
=~ のリンク切れ

### ISSUE THREAD

**Issue by k-takata** [vim-jp/vimdoc-ja-working#124]
Web 上で見ると、[assert_match()](http://vim-jp.org/vimdoc-ja/eval.html#assert_match()) の2段落目先頭の `=~` のリンクが切れています。
Vim 上で `=~` にカーソルを置いて <kbd>Ctrl+]</kbd> を実行すると、`expr-=~` に飛ぶので、Web 上でも同様に飛べるようにしたいです。

**Comment by koron** [comment]
コレなんで切れてるんだ?

**Comment by k-takata** [comment]
`expr-=~` のタグはあっても `=~` のタグはないのだと思います。

**Comment by koron** [comment]
だとすると、どうして Vim では飛べるんだろう?
ジャンプする時に `expr-` を補っているってことかしら?

**Comment by koron** [comment]
1. `$VIMRUNTIME/doc/tags` の中には無さそう
2.  `grep -nr expr- src/` した限りでは、 `expr-` を補っている場所はなさ気

なんでジャンプできるの? デバッガで追うべき?

**Comment by k-takata** [comment]
単に部分一致で検索しているだけではないでしょうか。コードは見ていませんが。

**Comment by h-east** [comment]
> 単に部分一致で検索しているだけではないでしょうか。コードは見ていませんが。

その通りです。
`:h {subject}` にヘルプを検索する時の洗練されたアルゴリズムが書かれています。
ですので、`:h ctrl-r` すると `netrw-ctrl-r` のヘルプを表示してしまいます(苦笑)
`:h CTRL-R` か `:h ¥<ctrl-r` でお望みのヘルプに飛びます。

**Comment by koron** [comment]
@h-east ありがとうございます!

>`:h {subject}` にヘルプを検索する時の洗練されたアルゴリズムが書かれています。

これの同等品を実装したほうが、見逃す可能性が減らせてよいのかもしれない…

**Comment by koron** [comment]
参考: http://vim-jp.org/vimdoc-ja/helphelp.html#{subject}
