### ISSUE TITLE
terminal.jaxタイポ

### ISSUE THREAD

**Issue by gashihiko** [vim-jp/vimdoc-ja-working#1256]
>入力したキーを別のものに読み返させるには端末モードマッピング、詳細は |:tmap| を
参照してください。

`:s/読み返/読み替え/`

ですかね？

**Comment by tsuyoshicho** [comment]
https://github.com/vim-jp/vimdoc-ja-working/pull/1258
修正つくりました、一応見ておいていただけますか? @gashihiko さん
