### ISSUE TITLE
usr_24.jax L342 について

### ISSUE THREAD

**Issue by nakinor** [vim-jp/vimdoc-ja-working#128]
`ir = ~` の部分です。

日本語訳では下記のようになっていますが、
> "v はレジスタの指定、"yiw" は yank-inner-word (単語をヤンクする) です。さて、
> 元のファイルに戻り、挿入モードを開始して次のように入力します:
>
>	ir = ~
>
> ここで、CTRL-R v を押して関数の名前を挿入します:

本家では下記のようになっています。
> "v is the register specification, "yiw" is yank-inner-word.  Now edit the file
> where the new line is to be inserted, and type the first letters:
>
>	r = ~
>
> Now use CTRL-R v to insert the function name:

typo かと思うのですが、「挿入モードを開始して」の i を含めているのでしょうか？

**Comment by k-takata** [comment]
typoじゃないですかね。翻訳で変更する理由はないと思います。
