### ISSUE TITLE
usr_04.jax L399 の "aw" の説明について

### ISSUE THREAD

**Issue by nakinor** [vim-jp/vimdoc-ja-working#129]
「"daw" は "Delete A Word"」に合わせて「"aw" は "A Word"」にした方が
良いのではないかと思います。

日本語訳では下記のようになっています。
> "daw" の "d" は削除オペレータです。"aw" はテキストオブジェクトです。"aw" は "a
> word" の意味です。つまり "daw" は "Delete A Word" という意味になります。正確に
> は、単語の後の空白も削除されます (単語が行末にある場合は、行末までのすべての空
> 白が削除されます)。

原文では下記のようになっています。
> The "d" of "daw" is the delete operator.  "aw" is a text object.  Hint: "aw"
> stands for "A Word".  Thus "daw" is "Delete A Word".  To be precise, the white
> space after the word is also deleted (the white space before the word at the
> end of the line).

**Comment by k-takata** [comment]
fixed
