### ISSUE TITLE
README.md の冒頭に vimdoc-ja へのリンクを記載する？

### ISSUE THREAD

**Issue by tyru** [vim-jp/vimdoc-ja-working#13]
## 理由

* 将来このリポジトリを間違えて clone してしまうユーザの方もいるのではないかと思いました。

## 修正案

* vimdoc-ja との違いを記載しても良いですが、せめて各リンクを記載するだけでも良いと思います。
  * https://github.com/vim-jp/vimdoc-ja/issues/223
  * https://github.com/vim-jp/vimdoc-ja
* いっそこのリポジトリにはリンクのみ記載する？
* 現状だと README.md 等の変更も vimdoc-ja に反映されてしまう？ようなので、具体的には [ここ](https://github.com/vim-jp/vimdoc-ja-working/blob/5bdf9f6f92ca460d5ae6a90f2d678c56124885db/tools/deploy-master.sh#L15) を `doc` と `syntax` だけ `git add` するよう変えればいけるんじゃないかと思いました

**Comment by koron** [comment]
> doc と syntax だけ git add するよう変えればいけるんじゃないか

逆が良いです。 README.md などを exclude して `add --all` するほうが
将来なにかが増えた時とかに驚きが少なくなります。

**Comment by koron** [comment]
いやそれも違うか。

https://github.com/vim-jp/vimdoc-ja-working/blob/5bdf9f6f92ca460d5ae6a90f2d678c56124885db/tools/deploy-master.sh#L12 で

    rsync -rlptD --delete-after README.md ${dir}/README.md

しているんだから、、このソースを変えれば良いだけか。

**Comment by tyru** [comment]
すぐ上で持ってきてたw
確かにそれが良さそうです。

**Comment by koron** [comment]
@tyru README-dist.md に分離し、実際にそれが vim-jp/vimdoc-ja に反映されるのを確認しました。

あとは任せますので、双方とも適宜修正をお願いします。

**Comment by nakinor** [comment]
> 日本語に翻訳したVimの付属ドキュメントを翻訳するためのプロジェクトです。

単純に「Vim 付属のヘルプを日本語に翻訳するためのプロジェクトです。」で良いと思います。

**Comment by koron** [comment]
@nakinor please make a PR

**Comment by tyru** [comment]
(;ﾟДﾟ)
(;つД⊂)ｺﾞｼｺﾞｼ
(;ﾟДﾟ) …

今見たら元から vimdoc-ja が利用者向けで vimdoc-ja-working が翻訳者向けな事がちゃんと書いてありました…
本当にお騒がせして申し訳ありませんでした…

自分としては今の README.md に書かれてる内容で十分伝わると思います orz

**Comment by k-takata** [comment]
分離してわかりやすくなったと思います。
あとは、姉妹プロジェクトとして lang-ja へのリンクを載せたいですね。

**Comment by koron** [comment]
#15 で対応したということで閉じます。

今後、似たような要望が出た場合は別のissueを立ててください。
