### ISSUE TITLE
usr_41.jax L759 reltimefloat() について

### ISSUE THREAD

**Issue by nakinor** [vim-jp/vimdoc-ja-working#132]
関数一覧 -> 日付と時刻 の部分。

> 「reltimefloat()    convert reltime() result to a Float」

の部分はほんにゃく忘れだと思いますが、すぐ上の

> 「reltime()の結果を文字列に変換する」

に合わせて「reltime()の結果を浮動小数点に変換する」
になるのでしょうか(指数表示されますけど)？

**Comment by k-takata** [comment]
fixed
