### ISSUE TITLE
usr_05.jax の L231 の倒置について

### ISSUE THREAD

**Issue by nakinor** [vim-jp/vimdoc-ja-working#133]
日本語訳の下記の部分ですが

> このコマンドを入力するときの注意点。
> \<F5> 見たままのは 4 文字の文字列として入力してください。\<Esc> も同じで
> す。\<Esc> キーを押すのではなく、5 文字の文字列として入力してください。

「\<F5> 見たままのは 4 文字」→「\<F5> は見たままの 4 文字」
とした方が読み易いと思いますが、いかがでしょうか？

**Comment by k-takata** [comment]
fixed
