### ISSUE TITLE
usr_21.jax の L201 の未訳部分について

### ISSUE THREAD

**Issue by nakinor** [vim-jp/vimdoc-ja-working#134]
日本語訳では下記のようになっています。

> 合にはまず "q" を押して表示を止めます。プロンプトが表示されるので:
>
>        Type number and <Enter> (empty cancels): ~
>
> "2" を入力して <Enter> を押し、二番目のファイルを開きます。

ja.po にはこうあります。

> msgid "Type number and <Enter> (empty cancels): "
> msgstr "番号と<Enter>を入力してください (空でキャンセル): "

わたしの Vim ではエラー等のメッセージが英語表記なので確認できませんが、
下記のように ja.po と合わせた方が良いと思いますが、いかがでしょうか？

> 合にはまず "q" を押して表示を止めます。プロンプトが表示されるので:
>
>         番号と<Enter>を入力してください (空でキャンセル): ~
>
> "2" を入力して <Enter> を押し、二番目のファイルを開きます。

**Comment by k-takata** [comment]
日本語メッセージは、もしかしたら訳注として入れておく方がよいのではないでしょうか。
他にもメッセージが英語日本語併記になっていた箇所はあったはずです。（ユーザーマニュアルかリファレンスかは忘れましたが。）
他の場所に合わせるのがよいかと思います。

**Comment by nakinor** [comment]
日英併記があるのは、ユーザーマニュアルの中では usr_11.jax だけですかね。
リファレンスの方でも見つかるかもしれません(が、ちょっと疲れました)。

**Comment by nakinor** [comment]
undo も併記されていますね。
各人の環境によって表示は異なってしまうので、日本語版としてはすべて併記が望ましいのでしょうけれど、それが煩わしく感じる場合もあるわけで……
ここは説明の核心部分ではないので、そのままにしておきますか。
ありがとうございました。
