### ISSUE TITLE
helphelp.jax について。未訳？

### ISSUE THREAD

**Issue by nakinor** [vim-jp/vimdoc-ja-working#140]
### 1. 原文 L38-39 にある下記の部分ですが、jax には訳されていないようです。

> But when a tag exists it is taken literally:
> :help :? jump to help for ":?"

cmdline.jax の *:?* 項目に飛ぶのですが、直訳だとこうなるでしょうか。

> ですが、タグが存在するときは、文字通りにとられます。
> :help :? ":?" のヘルプを開く

しかし、挙動と説明が一致していないのでうまくない……
正規表現とも関係していそうですし、よくわかりません。

### 2. 原文 L81-82 にある下記の部分ですが、

> :help index
> :tselect /.*mode

.jax では下記のようになっており、異なっています。

> :help index| :tse z.

### 3. 小見出し

「3. ヘルプファイルの書き方」中の「タグ」と「ハイライト表示」の部分。
原文にはついていませんが、下線をつけて小見出しにした方がわかりやすいと
思いました。
(原文にはついておらず訳文に付いている例は、例えば usr_02 の THE VIM COMMAND とか)

**Comment by k-takata** [comment]
> しかし、挙動と説明が一致していないのでうまくない……

半月ほど前に挙動が修正されてませんでしたっけ？
help が加筆されたのも最近ですよね。訳はそれで合っていると思います。

**Comment by nakinor** [comment]
すみません。訳文は(未訳にしてでも)最新版になっているものと思い込んでいました。
en/*.txt を見ていませんでした。

**Comment by nakinor** [comment]
ありがとうございます。
3 番目は本質ではないでふからね……
