### ISSUE TITLE
tips.jax について。補足事項？

### ISSUE THREAD

**Issue by nakinor** [vim-jp/vimdoc-ja-working#141]
L231-232 にある下記の部分ですが、原文にはないようです。
何か補足的な説明なのでしょうか？
{訳注：} とかで囲む？

> これは 'modifiable' オプションがオフのときは機能しません。代わりにビジュアル
> モードで|v_g_CTRL-G|を使ってください。

原文 L220-228

> You might want to reset 'hlsearch' or do ":nohlsearch".
> Add the 'e' flag if you don't want an error when there are no matches.
> 
> An alternative is using |v_g_CTRL-G| in Visual mode.
> 
> If you want to find matches in multiple files use |:vimgrep|.
> 
> 							*count-bytes*
> If you want to count bytes, you can use this:

日本語訳 L224-235

> 'hlsearch' をリセットするか、":nohlsearch" をしたくなるかもしれません。
> マッチが1個もないときにエラーになってほしくなければフラグ 'e' をつけます。
>
> 別の方法としては、ビジュアルモードで|v_g_CTRL-G|を使います。
>
> 複数のファイルから検索したければ|:vimgrep|を使います。
>
> これは 'modifiable' オプションがオフのときは機能しません。代わりにビジュアル
> モードで|v_g_CTRL-G|を使ってください。
>
>							*count-bytes*
> バイト数を数えるにはこれを使ってください。

**Comment by k-takata** [comment]
ずいぶん昔に原文から削除されたようですね。 https://github.com/vim-jp/vimdoc-ja-working/commit/6572231867c6b4f6a2047342fcdb4b9828929f49#diff-ebaca88b25fc49072595bcd8379b3b27L217

**Comment by nakinor** [comment]
ありがとうございます。
