### ISSUE TITLE
option.jax 未訳部分

### ISSUE THREAD

**Issue by k-takata** [vim-jp/vimdoc-ja-working#17]
option.jax の以下の項目に、未訳部分が残っています。

* [ ] `'cot'`
* [x] `'eb'`
* [ ] `'et'`
* [ ] `'isk'`
* [ ] `'mmt'`
* [ ] `'nf'`
* [ ] `'ri'`
* [ ] `'ru'`
* [ ] `'sm'`
* [ ] `'si'`
* [ ] `'sta'`
* [ ] `'sts'`
* [ ] `'tw'`
* [ ] `'wm'`
* [ ] `'spl'`
* [ ] `'swb'`
* [ ] `viminfo-%`

**Comment by koron** [comment]
related with #25

**Comment by k-takata** [comment]
#44 ですべて翻訳が済んだようですので、マージ前ですが一足先に閉じます。
