### ISSUE TITLE
gh-pages: concealされている文字が表示されている

### ISSUE THREAD

**Issue by k-takata** [vim-jp/vimdoc-ja-working#1760]
#1434 で Vim のバージョンを 8.2.0020 から 9.1.0065 に更新したことにより、HTML に変換後のページで `~`, `>`, `<` などの conceal されている文字が表示されるようになってしまっています。(vimdoc-en でも同じ問題が起きています。)

差分: https://github.com/vim-jp/vimdoc-ja/commit/f500c7f034b7c6f3de56a98888df6c148bbf6b4d

カラースキームの更新による影響かもしれません。

**Comment by h-east** [comment]
使用しているカラースキームのハイライト `Ignore` グループの `guifg` または `ctermfg` の値が `NONE` だと表示されてしまうようです。

**Comment by h-east** [comment]
カラースキームの `hi Ignore` の設定を無理やり上書きすることで回避できそうです。
(これがBestなsolutionかは今のところ分からない)

```patch
diff --git a/tools/makehtml.vim b/tools/makehtml.vim
index 2d3f8fb9..f3b3391c 100644
--- a/tools/makehtml.vim
+++ b/tools/makehtml.vim
@@ -24,6 +24,9 @@ function! MakeHtmlAll(...)
   let s:log = []
   call MakeTagsFile()
   echo ""
+  " Avoid problem with highlight group helpIgnore character not being removed
+  execute printf("hi Ignore guifg=#ffffff ctermfg=white")
+
   let files = split(glob('*.??[tx]'), '\n')
   for i in range(len(files))
     let file = files[i]
```

**Comment by k-takata** [comment]
カラースキームの設定の上書きで行けるのならそれでよさそうな気がします。
execute と printf を使っているのは何か意味がありますか？

**Comment by h-east** [comment]
> execute と printf を使っているのは何か意味がありますか？

あ、ないです。参考にしたコードで使われていたけど、`%～' 使ってないから不要ですね。
後で PR 出します。
