### ISSUE TITLE
誤訳 (:h synIDattr) in eval.jax

### ISSUE THREAD

**Issue by h-east** [vim-jp/vimdoc-ja-working#18]
日本語訳だけおかしいようです。
https://github.com/vim-jp/vimdoc-ja-working/blob/master/doc/eval.jax#L6174-L6175
```
		例(カーソルの下の構文アイテムの名前を表示する): >
	:echo synIDattr(synIDtrans(synID(line("."), col("."), 1)), "fg")
```
最新en
```
                Example (echoes the color of the syntax item under the
                cursor):
        :echo synIDattr(synIDtrans(synID(line("."), col("."), 1)), "fg")
```

**Comment by h-east** [comment]
それは、`synIDattr()`の第2引数が`"name"`の場合ですよね？
`"fg"`の場合は`構文アイテムのカラー名`等と訳せば良いかな？

**Comment by h-east** [comment]
番号の場合もあるので`英文のまま構文アイテムのカラー`でいいのかも。

**Comment by mattn** [comment]
あ、ミスってました。そうですね。色名って言っちゃうと Windows の場合の数字が返る場合でモニョるので、`色`で良いと思います。

**Comment by h-east** [comment]
直接編集して直しちゃった。(`カラー`にしました)
https://github.com/vim-jp/vimdoc-ja-working/commit/c4e14fcb73d6f340f69173a8f60e3ce3a0170eab
