### ISSUE TITLE
Terminal-Job 及び Terminal-Normal の訳語

### ISSUE THREAD

**Issue by koron** [vim-jp/vimdoc-ja-working#186]
`:terminal` の追加に伴い `Terminal-Job` 及び `Terminal-Normal` という
両モード並びに用語が増えました。
これの訳語をどうするかを相談したいです。

現在進行中の翻訳作業 (#184) では、そのまま `Terminal-Job` と `Terminal-Normal` にしています。

候補としては

1. そのまま `Terminal-Job` と `Terminal-Normal` のまま
2. `端末ジョブモード` と `端末ノーマルモード`
3. 他にアイデア、翻訳案があれば

原文も近い将来変わる可能性がないわけではないので、
今この議論をすること自体が無駄になる可能性はあります。
なお原文でも表記が一致していない部分があるので、
そのあたりは vim-dev に働きかけもしたほうが良いかもしれません。

**Comment by tyru** [comment]
> 2\. 端末ジョブモード と 端末ノーマルモード

これに一票です。

**Comment by k-takata** [comment]
あるいはそのままカタカナ書きで、ターミナルジョブモード、ターミナルノーマルモード とするか…。

ま、長いので、2. に1票かな。

> 原文も近い将来変わる可能性がないわけではないので、

8.1 として正式にリリースされたので、もう変わらないと思います。

**Comment by h-east** [comment]
私も　2. に1票。

で、一旦これで統一しましょうか。

Terminal window → 端末ウィンドウ
Terminal-Normal mode → 端末ノーマルモード
Terminal-Job mode → 端末ジョブモード

**Comment by h-east** [comment]
terminal buffer → 端末バッファ ？

**Comment by h-east** [comment]
はい、反対意見ないので上記訳でいきましょう。
