### ISSUE TITLE
句読点は統一するべきか

### ISSUE THREAD

**Issue by mattn** [vim-jp/vimdoc-ja-working#202]
```
E319: このバージョンではこのコマンドは利用できません, ごめんなさい
```
* 最後が「。」で終わる物、終わらない物
* 句読点に「、」が使われている物、「, 」(半角カンマとスペース1個)が使われている物

個人的には一般ユーザ向けの文章なので「, 」は無いかなと思ったのでしょうがどうでしょうか。

**Comment by mattn** [comment]
「、」の使用は11個、「, 」の使用は38個 (意外と多かった)

**Comment by k-takata** [comment]
lang-ja の翻訳メッセージは多くが「, 」になっていて、それを引用しているだけでは？
なので、メッセージの方の句読点をどうするかという話だと思います。

**Comment by mattn** [comment]
あー、失礼 ja.po の話をしていました。リポ違い！？

**Comment by k-takata** [comment]
https://github.com/vim-jp/lang-ja でお願いします。
