### ISSUE TITLE
helphelp.txtの誤訳

### ISSUE THREAD

**Issue by chiyof** [vim-jp/vimdoc-ja-working#203]
:helpgrepの項で、

{pattern} には Vim の正規表現を使用できますpattern。
'ignorecase' は影響しません。大文字と小文字を**区別する
には** "\c" を使ってください。

とありますが、原文では

{pattern} is used as a Vim regexp |pattern|.
'ignorecase' is not used, add "\c" to ignore case.

とあり、意味が逆です。

**Comment by Milly** [comment]
前の行も
```
{pattern} には Vim の正規表現|pattern|を使用できます。
```
のほうが自然ですね。

**Comment by crazymaster** [comment]
Fixed by c0fbffe
