### ISSUE TITLE
8.1もリリースされたことですし、ここらで一気に有志で翻訳作業やりませんか？

### ISSUE THREAD

**Issue by h-east** [vim-jp/vimdoc-ja-working#207]
あんまり本家に追従出来ていないようですし??。そろそろガッとやった方が良い気がしてきました。

2018/05/31
`vimdoc-ja-working/en/*.txt` と Vim 8.1.0026 の `runtime/doc/*.txt` で変更情報作成。

|ファイル名|行数|追加行数|削除行数|作業者|メモ|
|:--------|---:|---:|---:|:---|:---|
|~~arabic.txt~~|322|21(+)|21(-)|mnishz|完了|
|~~autocmd.txt~~|1593|119(+)|12(-)|mnishz|完了|
|~~change.txt~~|1882|53(+)|3(-)|mnishz|完了|
|~~channel.txt~~|774|26(+)|15(-)|h-east|完了|
|~~cmdline.txt~~|1166|17(+)|7(-)|t-mochizuki|完了|
|~~debug.txt~~|175|1(+)|1(-)|mnishz|完了|
|~~debugger.txt~~|142|6(+)|4(-)|mnishz|完了|
|~~develop.txt~~|566|37(+)|5(-)|mnishz|完了|
|~~diff.txt~~|444|6(+)|6(-)|mnishz|完了|
|~~digraph.txt~~|1491|1(+)|1(-)|mnishz|完了|
|~~editing.txt~~|1750|22(+)|16(-)|mnishz|完了|
|~~eval.txt~~|11538|1148(+)|302(-)|mnishz|完了|
|~~farsi.txt~~|269|1(+)|1(-)|mnishz|完了|
|~~filetype.txt~~|698|40(+)|29(-)|mnishz|完了|
|~~fold.txt~~|604|3(+)|3(-)|mnishz|完了|
|~~ft_ada.txt~~|515|2(+)|2(-)|mnishz|完了|
|~~ft_rust.txt~~|237|New||t-mochizuki|完了|
|~~ft_sql.txt~~|780|1(+)|1(-)|mnishz|完了|
|~~gui.txt~~|1078|62(+)|7(-)|mnishz|完了|
|~~gui_w32.txt~~|454|1(+)|1(-)|mnishz|完了|
|~~gui_x11.txt~~|724|121(+)|8(-)|mnishz|完了|
|~~hangulin.txt~~|112|9(+)|9(-)|mnishz|完了|
|hebrew.txt|142|1(+)|1(-)||需要なし？|
|~~help.txt~~|228|4(+)|1(-)|mnishz|完了|
|~~help.txt~~|373|1(+)|1(-)|mnishz|完了|
|~~howto.txt~~|96|1(+)|1(-)|mnishz|完了|
|~~if_cscop.txt~~|487|8(+)|25(-)|mnishz|完了|
|~~if_lua.txt~~|436|1(+)|1(-)|mnishz|完了|
|~~if_mzsch.txt~~|315|6(+)|3(-)|mnishz|完了|
|~~if_ole.txt~~|205|3(+)|3(-)|mnishz|完了|
|~~if_perl.txt~~|306|4(+)|4(-)|mnishz|完了|
|~~if_pyth.txt~~|927|27(+)|6(-)|mnishz|完了|
|~~if_ruby.txt~~|236|4(+)|1(-)|t-mochizuki|完了|
|~~if_sniff.txt~~|11|1(+)|1(-)|mnishz|完了|
|~~if_tcl.txt~~|547|1(+)|1(-)|mnishz|完了|
|~~indent.txt~~|1159|26(+)|6(-)|mnishz|完了|
|~~index.txt~~|1660|6(+)|2(-)|mnishz|完了|
|~~insert.txt~~|2008|31(+)|27(-)|mnishz|完了|
|~~intro.txt~~|909|2(+)|2(-)|mnishz|完了|
|~~map.txt~~|1555|26(+)|8(-)|mnishz|完了|
|~~mbyte.txt~~|1470|37(+)|5(-)|mnishz|完了|
|~~message.txt~~|869|6(+)|8(-)|mnishz|完了|
|~~mlang.txt~~|213|3(+)|3(-)|mnishz|完了|
|~~motion.txt~~|1343|9(+)|3(-)|mnishz|完了|
|~~netbeans.txt~~|1010|3(+)|3(-)|mnishz|完了|
|~~options.txt~~|9149|227(+)|99(-)|mnishz|完了|
|~~os_390.txt~~|134|1(+)|1(-)|mnishz|完了|
|~~os_amiga.txt~~|147|1(+)|1(-)|mnishz|完了|
|~~os_beos.txt~~|320|2(+)|2(-)|mnishz|完了|
|~~os_dos.txt~~|298|1(+)|1(-)|mnishz|完了|
|~~os_mac.txt~~|182|74(+)|10(-)|mnishz|完了|
|~~os_mint.txt~~|39|1(+)|1(-)|mnishz|完了|
|~~os_msdos.txt~~|15|1(+)|1(-)|mnishz|完了|
|~~os_os2.txt~~|13|1(+)|1(-)|mnishz|完了|
|~~os_qnx.txt~~|138|1(+)|1(-)|mnishz|完了|
|~~os_risc.txt~~|12|1(+)|1(-)|mnishz|完了|
|~~os_unix.txt~~|60|1(+)|1(-)|mnishz|完了|
|~~os_vms.txt~~|955|13(+)|13(-)|mnishz|完了|
|~~os_win32.txt~~|306|1(+)|1(-)|mnishz|完了|
|~~pattern.txt~~|1412|36(+)|22(-)|mnishz|完了|
|~~pi_getscript.txt~~|482|4(+)|4(-)|mnishz|完了|
|~~pi_gzip.txt~~|43|1(+)|1(-)|mnishz|完了|
|~~pi_logipat.txt~~|121|0(+)|0(-)||変更なし|
|~~pi_netrw.txt~~|4270|261(+)|96(-)|mnishz|完了|
|~~pi_paren.txt~~|60|1(+)|1(-)|mnishz|完了|
|~~pi_spec.txt~~|111|1(+)|1(-)|mnishz|完了|
|~~pi_tar.txt~~|151|1(+)|1(-)|mnishz|完了|
|~~pi_vimball.txt~~|276|1(+)|1(-)|mnishz|完了|
|~~pi_zip.txt~~|152|1(+)|1(-)|mnishz|完了|
|~~print.txt~~|755|33(+)|33(-)|mnishz|完了|
|~~quickfix.txt~~|1793|205(+)|20(-)|t-mochizuki|完了|
|~~quickref.txt~~|1448|15(+)|2(-)|mnishz|完了|
|~~quotes.txt~~|275|2(+)|2(-)|mnishz|完了|
|~~recover.txt~~|237|1(+)|1(-)|mnishz|完了|
|~~remote.txt~~|207|5(+)|3(-)|mnishz|完了|
|~~repeat.txt~~|1013|20(+)|1(-)|mnishz|完了|
|~~rileft.txt~~|124|1(+)|1(-)|mnishz|完了|
|~~russian.txt~~|74|1(+)|1(-)|mnishz|完了|
|~~scroll.txt~~|335|3(+)|1(-)|mnishz|完了|
|~~sign.txt~~|205|1(+)|1(-)|mnishz|完了|
|~~spell.txt~~|1649|12(+)|12(-)|homedm|完了|
|~~sponsor.txt~~|216|1(+)|1(-)|mnishz|完了|
|~~starting.txt~~|1686|22(+)|15(-)|mnishz|完了|
|~~syntax.txt~~|5481|45(+)|24(-)|mnishz|完了|
|~~tabpage.txt~~|475|4(+)|4(-)|mnishz|完了|
|~~tagsrch.txt~~|857|23(+)|22(-)|mnishz|完了|
|~~term.txt~~|970|33(+)|5(-)|mnishz|完了|
|~~terminal.txt~~|863|529(+)|93(-)|h-east|完了|
|~~tips.txt~~|534|1(+)|1(-)|mnishz|完了|
|~~uganda.txt~~|288|1(+)|1(-)|mnishz|完了|
|~~undo.txt~~|406|1(+)|1(-)|mnishz|完了|
|~~usr_01.txt~~|192|1(+)|1(-)|mnishz|完了|
|~~usr_02.txt~~|701|1(+)|1(-)|mnishz|完了|
|~~usr_03.txt~~|657|1(+)|1(-)|mnishz|完了|
|~~usr_04.txt~~|514|1(+)|1(-)|mnishz|完了|
|~~usr_05.txt~~|666|9(+)|1(-)|mnishz|完了|
|~~usr_06.txt~~|280|1(+)|1(-)|mnishz|完了|
|~~usr_07.txt~~|479|11(+)|11(-)|mnishz|完了|
|~~usr_08.txt~~|601|1(+)|1(-)|mnishz|完了|
|~~usr_09.txt~~|289|6(+)|6(-)|mnishz|完了|
|~~usr_10.txt~~|824|1(+)|1(-)|mnishz|完了|
|~~usr_11.txt~~|307|2(+)|2(-)|mnishz|完了|
|~~usr_12.txt~~|358|1(+)|1(-)|mnishz|完了|
|~~usr_20.txt~~|384|1(+)|1(-)|mnishz|完了|
|~~usr_21.txt~~|499|1(+)|1(-)|mnishz|完了|
|~~usr_22.txt~~|400|1(+)|1(-)|mnishz|完了|
|~~usr_23.txt~~|343|1(+)|1(-)|mnishz|完了|
|~~usr_24.txt~~|606|9(+)|9(-)|mnishz|完了|
|~~usr_25.txt~~|582|1(+)|1(-)|mnishz|完了|
|~~usr_26.txt~~|221|1(+)|1(-)|mnishz|完了|
|~~usr_27.txt~~|563|4(+)|4(-)|mnishz|完了|
|~~usr_28.txt~~|426|1(+)|1(-)|mnishz|完了|
|~~usr_29.txt~~|611|1(+)|1(-)|mnishz|完了|
|~~usr_30.txt~~|643|1(+)|1(-)|mnishz|完了|
|~~usr_31.txt~~|272|1(+)|1(-)|mnishz|完了|
|~~usr_32.txt~~|180|1(+)|1(-)|mnishz|完了|
|~~usr_40.txt~~|657|1(+)|1(-)|mnishz|完了|
|~~usr_41.txt~~|2595|15(+)|5(-)|mnishz|完了|
|~~usr_42.txt~~|365|1(+)|1(-)|mnishz|完了|
|~~usr_43.txt~~|179|1(+)|1(-)|mnishz|完了|
|~~usr_44.txt~~|719|1(+)|1(-)|mnishz|完了|
|~~usr_45.txt~~|419|1(+)|1(-)|mnishz|完了|
|~~usr_90.txt~~|498|1(+)|1(-)|mnishz|完了|
|~~usr_toc.txt~~|355|1(+)|1(-)|mnishz|完了|
|~~various.txt~~|731|34(+)|17(-)|mnishz|完了|
|~~version8.txt~~|25795|7764(+)|9(-)|Milly|完了|
|~~vi_diff.txt~~|1024|1(+)|1(-)|mnishz|完了|
|~~visual.txt~~|541|1(+)|1(-)|mnishz|完了|
|~~windows.txt~~|1314|37(+)|23(-)|t-mochizuki|完了|
|~~workshop.txt~~|98|1(+)|1(-)|mnishz|完了|

※ version4.txt, version5.txt, version6.txt, version7.txt, todo.txt は除外してます。

---
このmarkdown tableはこのBash scriptで作成しました。
(https://gist.github.com/h-east/22343834586bef55e4e0da5ce9d351bf)

**Comment by h-east** [comment]
`terminal.jax` 翻訳中。今は、`terminal-size-color`の所。今週末にはPR出せると思う。
PR https://github.com/vim-jp/vimdoc-ja-working/pull/209 はマージせずに閉じていい？

**Comment by mattn** [comment]
未翻訳部分の洗い出しをした方が良いと思いますね。

**Comment by h-east** [comment]
有志の方～

**Comment by mnishz** [comment]
他も調べてみたら、細かい変更が結構あるようです。
ここで聞くのがいいのか分からなかったのですが、
そういう場合まとめてcommitしたほうがいいですか？それとも個別にcommitしたほうがいいですか？

個別のほうがreviewはしやすいと思うのですが、commit logがいっぱいになるのも見にくいかと思いまして。

**Comment by h-east** [comment]
> そういう場合まとめてcommitしたほうがいいですか？それとも個別にcommitしたほうがいいですか？

個別で構わないと思います。

**Comment by h-east** [comment]
表更新しました。

**Comment by h-east** [comment]
(お願い)
変更量の少ないファイルはいきなりPRで良いと思いますが、変更量の多いやつはココに「このファイル今からやります」とコメントした方がいいかもです。
作業が被ってしまうともったいないので。

**Comment by t-mochizuki** [comment]
今から ft_rust.txt やります。できなかったら、すみません。。

**Comment by h-east** [comment]
もちろんギブアップありですよ:+1:
OSS活動は自分の出来ることを出来る時間で無理なくやることなので。
楽しくない苦労はしないでくださいね。

**Comment by Milly** [comment]
> version8.txt ...は除外

とあるのにやってしまいましたが、問題ありましたでしょうか。

**Comment by h-east** [comment]
@Milly  問題ないです。翻訳ありがとうございます。

**Comment by mnishz** [comment]
さて、そろそろ options にでも着手しますかね。。
レビューするのも大変だと思うので、量にもよりますが少しずつ push するかもしれません。

**Comment by t-mochizuki** [comment]
今週は作業できないと思うのですが、quickfix やります。

**Comment by mnishz** [comment]
今日偶然気がついてしまったのですが、@uakms さんがすでに以下のファイルに着手されている？？ -> https://github.com/vim-jp/vimdoc-ja-working/network
* hebrew
* os_mac
* spell

ということで次は channel でもやろうかな。使ったことないので、機能のお勉強からですかね。

**Comment by uakms** [comment]
旧 vimdoc-ja の issue に登録されてから 5 年くらい経っていても動きがなかったので呼び水にでもなればいいかなぁと思っていたのですがそびえ立つクソの山ブログを読んで毒水じゃんコレということで放置してあります (もともとは ofuro プロジェクトの texi を jax 形式に逆輸入したものです)。

mnishz さん、コレの存在は気にせずにどんどん作業を進めてください。私は追いかけて答え合わせをしていきます。

**Comment by mnishz** [comment]
おぉ、あんまりバックグラウンドがないのでよく理解できていないかもですけど。。
承知いたしました。

(いろんな人が参加してくれたほうが嬉しいには違いない。。)

**Comment by mnishz** [comment]
eval に着手いたしました。

**Comment by Milly** [comment]
vim_faq の upstream に vim_faq.jax 内の訳注の指摘などを投げて、それがマージされました。
https://github.com/chrisbra/vim_faq

本体じゃないので上記リストには入ってないですね。
そもそも取り込まれてる txt の Last update が2004年なのでめちゃくちゃ古いですね……。

というわけで vim_faq を作業中です。

**Comment by h-east** [comment]
vim_faqの存在を昨日知りました:sweat_smile:
vimdoc-jaには含まれていないので読んだことのある人少ないんじゃないかなぁ。
それと、情報が古いので "参考資料" 程度に留めておいた方が良い気がします。
(vim-users-jpの様に https://vim-jp.org/ 下に置いてしまうとか)
どうでしょう？
別Issue立てて議論しますか？

(@Milly  作業してもらってるのに水を差す感じになってすいません。)

**Comment by k-takata** [comment]
vimdoc-ja の master ブランチには含まれていませんが、ちゃんと https://vim-jp.org/vimdoc-ja/vim_faq.html で見えるようになっています。

**Comment by Milly** [comment]
chrisbra さんにPR投げたら2年越しくらいに更新が始まった。
なおURLなどは私が最新に更新してPR済、マージ済みです。

**Comment by homedm** [comment]
現在、spellの翻訳をしている方っていらっしゃいますか？いなければやろうと思っています。

**Comment by k-takata** [comment]
spellは #247 をベースに作業していただくのがよいと思います。

**Comment by h-east** [comment]
tips.txt, usr_05.txt, usr_09.txt, usr_11.txt, usr_41.txt, usr_42.txt, various.txt, version8.txt, windows.txt を最新に追従する作業やりました。今晩PR出します。

**Comment by h-east** [comment]
うぉっ、今気づいたんですけど、spell.txt は上の表だと追加12行、削除12行と楽勝ぽいですが、実は spell.jax ってenを未翻訳でかなりの量ぶち込んでいるので大変なのですね。

**Comment by mnishz** [comment]
そうなんですよね。この issue は 8.1 への対応なので、未翻訳部分は別 issue に分けてもいいような気もしますが、homedm さんはどうするつもりなのでしょうか。。
あと hebrew.txt に関しては日本語ファイルすら無いですね。ヘブライ語サポートのヘルプファイルを日本語で読みたい人がどれくらいいるか、という意味であまりモチベーションが上がらないです。。

**Comment by homedm** [comment]
8.1への対応の部分で若干入っている部分もかなりあるので分けるよりはまとめてしまったほうがよさそうに思います。
#247 でかなりの部分の翻訳をやって頂けているので、このissueでまだ翻訳されていないスペルファイルの生成の部分を進めようと考えています。

**Comment by h-east** [comment]
@homedm 了解です。大変ですがよろしくお願いします。ツラかったら手を挙げてください。出来る範囲でサポートします。

**Comment by homedm** [comment]
@h-east さんありがとうございます。
先ほど、 #247 を改めて眺めていたのですが、これ全部翻訳をやって頂けてますね...
ちょっと寝かせておきますといってますしもうしばらく待っていたほうが良いのでしょうか。
先にpi_netrw.txtのほうの翻訳を進めたほうが良い気もしてきました。

**Comment by h-east** [comment]
@homedm 作業されていた uakms さんはGitHubアカウント消失されているようなので spell.jax の翻訳を完成させた方が良いかと思います。

**Comment by tyru** [comment]
@uakms さんアイコンは退会した人のアイコンにしてるみたいですが、アクセスはできるのでアカウントまだ生きてると思います
https://github.com/uakms

**Comment by h-east** [comment]
@tyru あ、ほんとだ。Thanks! & 失礼しました。リアクションを待ってみようと思います。

**Comment by mnishz** [comment]
JFYIですが、以前にこのスレの上のほうでお伺いしたときは「どうぞ進めてください」とのことでした。
https://github.com/vim-jp/vimdoc-ja-working/issues/207#issuecomment-407719144

**Comment by Milly** [comment]
#325 にて vim_faq のPR、ただしWIP。

**Comment by h-east** [comment]
大物以外は私がやってます。あと5つ:+1:。明日中にはPR出します。

**Comment by mnishz** [comment]
VimConf もアドベントカレンダーの記事も終えたし、pi_netrw.txt をやり終えて来年を迎えたい！
ということで開始します。
このヘルプが `:e.` で開くやつだとさっき分かった。。
プリフィックスの "pi" は plugin のことかな？

**Comment by h-east** [comment]
textprop.txt 翻訳中です。

**Comment by h-east** [comment]
現在の未着手ファイルです。作業ボリュームは「追加行数」と「削除行数」を見ればわかります。
これくらいだったらやれそうでしょ？ご新規さんの参入をお待ちしてます:+1:

|ファイル名|行数|追加行数|削除行数|作業者|メモ|
|:--------|---:|---:|---:|:---|:---|
|help.txt|237|7(+)|3(-)|||
|intro.txt|903|24(+)|30(-)|||
|message.txt|861|1(+)|9(-)|||
|sign.txt|326|2(+)|2(-)|||
|syntax.txt|5554|22(+)|2(-)|||
|textprop.txt|117|5(+)|2(-)|||

**Comment by h-east** [comment]
現在(2019/03/29)の未着手ファイルです。作業ボリュームは「追加行数」と「削除行数」を見ればわかります。
どなたかやっていただけると嬉しいなぁ。(私は今週末は作業できないです)

|ファイル名|行数|追加行数|削除行数|作業者|メモ|
|:--------|---:|---:|---:|:---|:---|
|channel.txt|834|5(+)|4(-)|||
|eval.txt|12616|19(+)|3(-)|||
|if_lua.txt|473|50(+)|14(-)|||
|if_ruby.txt|251|12(+)|2(-)|||
|index.txt|1711|4(+)|3(-)|||
|options.txt|9303|12(+)|2(-)|||
|tagsrch.txt|865|2(+)|3(-)|||
|various.txt|747|2(+)|2(-)|||

更新不要の 123 ファイルの表示は省略しています。

※  version4.txt, version5.txt, version6.txt, version7.txt, todo.txt は除外してま
す。

**Comment by h-east** [comment]
> どなたかやっていただけると嬉しいなぁ。

@hiromi-mi @mnishz 対応ありがとうございます 🙇

**Comment by mnishz** [comment]
> 
> 
> > どなたかやっていただけると嬉しいなぁ。
> 
> @hiromi-mi @mnishz 対応ありがとうございます bowing_man

いえいえ、こちらこそいつもドキュメントの更新どうもありがとうございます。

**Comment by h-east** [comment]
2019/04/29 AM8;30 JST 時点の未翻訳ファイル。1人じゃ無理ー:sweat_smile:

|ファイル名|行数|追加行数|削除行数|作業者|メモ|
|:--------|---:|---:|---:|:---|:---|
|autocmd.txt|1646|9(+)|9(-)|||
|editing.txt|1771|33(+)|12(-)|||
|eval.txt|12882|69(+)|15(-)|||
|gui.txt|1231|138(+)|5(-)|||
|gui_w32.txt|465|12(+)|1(-)|||
|gui_x11.txt|738|2(+)|2(-)|||
|index.txt|1714|5(+)|3(-)|||
|map.txt|1572|12(+)|10(-)|||
|mbyte.txt|1472|15(+)|0(-)|||
|options.txt|8833|57(+)|527(-)|||
|print.txt|756|3(+)|3(-)|||
|tagsrch.txt|941|68(+)|1(-)|||
|term.txt|990|2(+)|2(-)|||
|usr_11.txt|315|8(+)|1(-)|||
|usr_22.txt|414|19(+)|5(-)|||
|usr_41.txt|2638|1(+)|1(-)|||
|various.txt|750|15(+)|12(-)|||
|vi_diff.txt|1098|79(+)|5(-)|||

更新不要の 113 ファイルの表示は省略しています。

※ version4.txt, version5.txt, version6.txt, version7.txt, todo.txt は除外してま
す。

**Comment by hiromi-mi** [comment]
`gui_x11.txt`, `print.txt`, `term.txt` について上記の表では追従未了とありますがそれぞれ #518, #521, #522 により完了しているようです。h_east さんありがとうございます。

**Comment by h-east** [comment]
@hiromi-mi `git pull`する前に表生成スクリプトを実行してしまったようです。失礼しました。
あと、5月5日の 8.1.1280 でかなりの数のファイルが更新されたので表を更新しました。

**Comment by mnishz** [comment]
change.txt やってます

**Comment by h-east** [comment]
未翻訳ファイル情報を更新しました。あと4ファイル！！
https://github.com/vim-jp/vimdoc-ja-working/issues/207#issuecomment-487425174

私はそろそろVPD(Vim patchダイジェスト)を進めていかないといけないので、こっちは手薄になります。
よろしくお願いします:bow:

**Comment by mnishz** [comment]
pattern.jax やります。

**Comment by h-east** [comment]
options.jax やってます。

**Comment by h-east** [comment]
2019/05/30 12:57 JST時点の未翻訳ファイル。
誰かやりませんか？

|ファイル名|行数|追加行数|削除行数|作業者|メモ|
|:--------|---:|---:|---:|:---|:---|
|popup.txt|446|New||||
|tagsrch.txt|920|108(+)|62(-)|||

**Comment by k-takata** [comment]
popup.txt はもう少し仕様が固まってからでもいいのでは？

**Comment by h-east** [comment]
2019/06/17 12:00 JST時点の未翻訳ファイル。

|ファイル名|行数|追加行数|削除行数|作業者|メモ|
|:--------|---:|---:|---:|:---|:---|
|autocmd.txt|1663|28(+)|10(-)|||
|eval.txt|13281|27(+)|5(-)|||
|popup.txt|646|New||h-east|PR済。もうすぐmergeします|

Hey! Come on!

**Comment by k-takata** [comment]
すでにタイトルの作業は完了してますし、コメントが多すぎて途中で省略されてますし、そろそろ新しいissueを立てて仕切りなおしてもいいんじゃないですかね。

**Comment by h-east** [comment]
新しいIssueを立てたのでこのIssue閉じます。
すべてはここからはじまった。

**Comment by mnishz** [comment]
私の vim-jp への入り口がここでした。ありがとうございました。
