### ISSUE TITLE
TermDebug ではなく Termdebug だと思います

### ISSUE THREAD

**Issue by t-mochizuki** [vim-jp/vimdoc-ja-working#208]
`:TermDebug` とありますがタイポだと思われます。`:Termdebug` に変更したほうが良いと思います。

### 関連URL

- http://vim-jp.org/vimdoc-ja/terminal.html#terminal-debug
- https://github.com/vim-jp/vimdoc-ja/blob/master/doc/terminal.jax

**Comment by uakms** [comment]
本家側の更新によるものなので、vimdoc-ja-working/en/terminal.txt の該当する部分も一緒に更新をお願いします。

https://github.com/vim/vim/commit/24a98a0eb77245adc50facad8b735b20bfd31a7e#diff-aa095c2f3891d858d5cd11c202a83302

**Comment by t-mochizuki** [comment]
マージされたので close
