### ISSUE TITLE
Mistranslation (:help 'sidescrolloff') in options.jax

### ISSUE THREAD

**Issue by ryunix** [vim-jp/vimdoc-ja-working#22]
「オプション 'nowrap' がオフのとき」となっていますが、「オプション 'wrap' がオフのとき」か「オプション 'nowrap' がオンのとき」が正しいと思います。
前者は他のところでもよく見られる表記ですが、後者の方がより原文に近いのかなと思いました。(判断できなかったため、報告だけしておきます)
https://github.com/vim-jp/vimdoc-ja-working/blob/dc1737a/doc/options.jax#L6805

原文では「if 'nowrap' is set」となっています。
https://github.com/vim-jp/vimdoc-ja-working/blob/dc1737a/en/options.txt#L6683

**Comment by crazymaster** [comment]
「オプション 'wrap' がオフのとき」の表記の方が多いようなので、そちらを採用しました。
