### ISSUE TITLE
サイトに GitHub の編集画面へのリンクを貼りたい

### ISSUE THREAD

**Issue by mattn** [vim-jp/vimdoc-ja-working#245]
動機はこちら

https://qiita.com/amay077/items/8823376f307235a7f651

要は

http://vim-jp.org/vimdoc-ja/usr_01.html

このページに設ける「GitHub で編集」みたいなリンクをクリックすると

https://github.com/vim-jp/vimdoc-ja-working/edit/master/doc/usr_01.jax

この画面を出すという物です。参入障壁が低くなり良い気がしますが、如何でしょうか。

**Comment by ujihisa** [comment]
https://github.com/vim-jp/vimdoc-ja-working/edit/master/doc/usr_01.jax

の場合githubにログインしてなかったらログインページがでるので、元のmicrosoftのやつみたいに

https://github.com/vim-jp/vimdoc-ja-working/blob/master/doc/usr_01.jax

一旦こっち側のページを噛ませた方が直感的かな?

**Comment by mattn** [comment]
そうですね。そっちで行きましょう。

**Comment by ujihisa** [comment]
[つづきはwebで](https://github.com/vim-jp/vimdoc-ja/pull/242)
