### ISSUE TITLE
vimdoc-ja/doc/tags-ja もdeployする

### ISSUE THREAD

**Issue by h-east** [vim-jp/vimdoc-ja-working#268]
これ、やってない理由なんかあるんでしたっけ？
ローカルでgit pull後に毎回 `:helptags`するの忘れがち。

**Comment by mattn** [comment]
賛否両論ありますね。プラグインマネージャによるインストールだと、ドキュメントとしてプラグインが配布されてる場合に作者がタグ生成し忘れてたりすると git diff が出ちゃうので、プラグイン界隈では doc/tags* は同梱しないというのが一般的なんですよね。

**Comment by h-east** [comment]
CIで自動生成するので「タグ生成し忘れ」は発生しないし同梱してもいいかなと思っています。

**Comment by koron** [comment]
いまざっくりみてたら vimdoc-ja のほうで .gitignore に指定しているんですね。

https://github.com/vim-jp/vimdoc-ja/commit/a2f1f07dd1f27953f823efb820bd50471ca9d41a

@crazymaster doc/tags-ja を含める(= vimdoc-ja の .gitignoreから外す) ことについてなにか意見はありますか?

**Comment by koron** [comment]
もともとはこれか。

https://github.com/vim-jp/vimdoc-ja/issues/70

**Comment by mattn** [comment]
あるとすれば

1. コントリビュータがドキュメントを修正
2. git commit -a しちゃう
3. tags-ja が含まれた PR がくる

とかでしょうか。

**Comment by h-east** [comment]
@mattn `vimdoc-ja-working/doc`の方は今まで通り`tags-ja`は含めないのでそういうことにはならないんじゃないでしょうか？

**Comment by mattn** [comment]
そうですね。なお僕のスタンスはどちらでもいいですが、いくぶんプラグインマネージャに関する知見が多い訳ではないので slack でも意見を募集しています。

**Comment by koron** [comment]
https://github.com/vim-jp/vimdoc-ja/issues/21 でも同じ議論をやってたんですね。
自分はもうすっかり忘れてる。

ざっくり見ると当時は
「どっちでも良い」vs「あったらプラグインマネージャはちょっと苦労するね」
みたいな感じで、「あるほうが良い」という立場は明確ではなかった。
だったらなしにしとこう、というくらいの判断だったんだと思います。

現時点においてどうするべきかは、僕は今も「どっちでも良い」

**Comment by h-east** [comment]
その議論してた時って`vimdoc-ja-working`あったんでしたっけ？

ちなみにローカルで`git pull`後に再度`:helptags`しても内容変わらないし、タイムスタンプは変わるけど、`git`は変更ファイルとみなさないです。

**Comment by mattn** [comment]
ctags の実装次第では出力される内容が違っちゃったりするんですよね。 TAG-ENCODING のありなしとか、universal-ctags だと中身も変わっちゃったりとか。

**Comment by mattn** [comment]
vim のバージョンにより出力されるタグが違うって事が起きた時にどうするかですね。

**Comment by h-east** [comment]
そもそも、プラグインマネージャが **無条件** でtags-jaを更新するのどうなの？って思いました。

とりあえず、`.vimrc`にこんなのを書いて運用してみます。
```vim
packadd! vimdoc-ja
let docdir = filter(split(&rtp, ','), 'v:val =~# "vimdoc-ja$"')[0] . '/doc'
let doctag = docdir . '/tags-ja'
if !filereadable(doctag) || getftime(doctag) < getftime(docdir)
  exec "helptags" docdir
endif
```

**Comment by h-east** [comment]
> vim標準のパッケージ機能ではタグファイルを含めることを推奨してますね

では含めることにしましょう。
（mattnさん、koronさんも「どっちでもいい」という意見なのも踏まえて）

**Comment by machakann** [comment]
今更ですけど、 `helphelp.txt` にもタグファイルは同梱するのが望ましい旨が書いてありました。

> \- Make a package with all the files and the tags file available for download.
>   Users can drop it in one of the "doc" directories and start use it.
>   Report this to Bram, so that he can add a link on www.vim.org.

**Comment by h-east** [comment]
> そもそも、プラグインマネージャが **無条件** でtags-jaを更新するのどうなの？って思いました。

この問題を改善するために、まずvim-plugにPRを投げました。
https://github.com/junegunn/vim-plug/pull/773
以下のいずれかの条件に一致したときのみ`:helptags`を実行するようにしました。
- doc/{tags,tags-??x} なファイルが存在しない
- doc/{tags,tags-??x} なファイルがgit管理されていない

他のVimプラグインマネージャも改善されて欲しい👍
