### ISSUE TITLE
doc/eval.jax を 8.0 へキャッチアップ

### ISSUE THREAD

**Issue by koron** [vim-jp/vimdoc-ja-working#27]
delived from #25

    en/eval.txt       | 2675 +++++++++++++++++++++++++++++++++++++++--------------

should work on catchup-8.0 branch

You can check differences at local with this command:

    git show 24fd5e10 -- en/{FILENAME}.txt

**Comment by k-takata** [comment]
差分の反映と、翻訳（できるところまで）やります。

**Comment by koron** [comment]
翻訳は #48 でやるということで、本 issue は close します。
