### ISSUE TITLE
"関わらず" の表記を変更する

### ISSUE THREAD

**Issue by h-east** [vim-jp/vimdoc-ja-working#286]
from https://github.com/vim-jp/vimdoc-ja-working/pull/285#issuecomment-403293658

> ところでTravis CIに "かかわらず" -> "関わらず" だと指摘されてしまったのですが、どうでしょうか。
私としては表記揺れ以前に漢字として正しくないように思うのですが。
https://kakuyomu.jp/works/1177354054881006064/episodes/1177354054883070722

みなさんの意見を見ると、ひらがなに統一する流れでOK？

もしくは、 @uakms さん提案の個別に対応するか？

**Comment by mnishz** [comment]
私はOKです。なんだったら全部地道に修正してもいいです。マンパワーで勝負。

以下単なるコメント。
元 issue の、"未然形「関わら」+ 打ち消しの助詞詞「ず」で「関わらず」" はあると思います。
文章的にはちょっと意味が違ってきて、「私はその人物には関わらず、～」みたいな使い方だと正解な気がします。

**Comment by uakms** [comment]
作業して下さる mnishz さんにすべてお任せします！

以下単なるオフトピ。
マニュアル内には despite や although などのように前後の文を否定や反転する意図のある「〜にもかかわらず」と、regardless のように無頓着とか無視する意図のある「〜にかかわらず」が存在しています。
「〜にもかかわらず」については、各種ブログの意見の通り「〜にも関わらず」「〜にも係わらず」「〜にも拘らず」ではなく、ひらがな表記の「〜にもかかわらず」にするので良いと思います。
「〜にかかわらず」については、関係・関心がないという意味合いであって、「拘」の語意うんぬんはもともと入っていないので、「〜に関わらず」と漢字を使っても良いと思うのですよね (例のブログでも「〜にも関わらず」について触れているのであって「〜に関わらず」については議論の対象としていませんもの)。
「関」は「とじる」「せき」という意味であって、「かかわる」というのは関連して作られた意味らしいですね。そしてその読み方が平成 22 年に登録されたと。語義にない漢字を使っちゃダメということであれば、やはり ひらがな にした方が良いのでしょうね。
ここで素人がうんぬんしても仕方がないので全部ひっくるめて ひらがな にしてしまうのが簡単だと思います。

と思ったらヒガシさんが作業してました。
