### ISSUE TITLE
`helpHeadline` のハイライトが適用されない。

### ISSUE THREAD

**Issue by Milly** [vim-jp/vimdoc-ja-working#311]
`helpHeadline` は大文字アルファベットのみで記述されることを想定しているため、日本語ではハイライトが適用されない。

#### syntax/help.vim
```vim
syn match helpHeadline		"^[-A-Z .][-A-Z0-9 .()]*[ \t]\+\*"me=e-1
```
<img width="533" alt="2018-09-08 17 50 59" src="https://user-images.githubusercontent.com/22977/45252365-e3e60d00-b38f-11e8-8d5b-fdff24b88170.png">

**Comment by tsuyoshicho** [comment]
いまとなっては、ヘルプは多言語(英語以外はUTF-8)な枠組みなので、syntax/help.vimにasciiで範囲指定しているようなのがあったら、軒並問題を起しそうですね

\# `*...*` とかの特定記号での範囲指定自体は問題ないけど...

**Comment by h-east** [comment]
本件に関しては、[日本語helpで独自に拡張された記法(小見出し)](https://github.com/vim-jp/vimdoc-ja-working/wiki/Guide#%E6%8B%A1%E5%BC%B5%E3%81%95%E3%82%8C%E3%81%9F%E8%A8%98%E6%B3%95)で対応しています。
https://github.com/vim-jp/vimdoc-ja/pull/275

(このissueが関連するものだと今気づきました 💦 )
