### ISSUE TITLE
doc/options.jax を 8.0 へキャッチアップ

### ISSUE THREAD

**Issue by koron** [vim-jp/vimdoc-ja-working#39]
delived from #25 and #17

    en/options.txt    |  360 ++++---

should work on catchup-8.0 branch

You can check differences at local with this command:

    git show 24fd5e10 -- en/options.txt

---

#17 の反映を忘れずに。

**Comment by koron** [comment]
#20 があるが、catch up としては別にissueが合ったほうが良いだろうとの判断で追加した。

**Comment by crazymaster** [comment]
まず https://github.com/vim-jp/vimdoc-ja-working/pull/20 を取り込んでからですね

**Comment by koron** [comment]
@crazymaster #44 に #20 を取り込んで、指摘事項を反映させました。

**Comment by koron** [comment]
competed
