### ISSUE TITLE
再キャッチアップとその後の修正

### ISSUE THREAD

**Issue by koron** [vim-jp/vimdoc-ja-working#42]
ターゲットは 8.0.0008 (https://github.com/vim/vim/commit/50ba526fbf3e9e5e0e6b0b3086a4d5df581ebc7e)
- [ ] 最新のランタイムをキャッチアップ
- [x] py3 のバージョン表示の位置 [*](https://github.com/vim-jp/vimdoc-ja-working/pull/40#discussion_r80057866)
  
  先行して修正してしまった at https://github.com/vim-jp/vimdoc-ja-working/pull/40

**Comment by k-takata** [comment]
24fd5e10468366bdbf6576a4817f507780ce950f で、Vim 8.0.0007 の英語版ファイルが `en` にコミットされていますが、英語版のみがコミットされているため、日本語版とのバージョンが不一致となってしまっています。修正が急務です。

**Comment by koron** [comment]
これ、それ以前に catch up 8.0 プロジェクト用のブランチを [マージしちゃった時点](https://github.com/vim-jp/vimdoc-ja-working/pull/37) で
他のファイルもそのようになっているはずです。

**Comment by k-takata** [comment]
あー、そうでしたか。いずれにせよ、en と doc が同期が取れていないのは早く直さないと…

**Comment by k-takata** [comment]
8.0.0168 までの追従が (#48 以外は) 完了したので、閉じます。
