### ISSUE TITLE
正規表現の文字クラス [:xxx:] 類の説明について

### ISSUE THREAD

**Issue by machakann** [vim-jp/vimdoc-ja-working#5]
[pattern.txt 1105行目](https://github.com/vim-jp/vimdoc-ja-working/blob/master/en/pattern.txt#L1105-L1108)
>	  These items only work for 8-bit characters, except [:lower:] and
>	  [:upper:] also work for multi-byte characters when using the new
>	  regexp engine.  In the future these items may work for multi-byte
>	  characters.

[pattern.jax 1090行目](https://github.com/vim-jp/vimdoc-ja-working/blob/8ba9c98a073a152145aa9789ece450a2eac456f1/doc/pattern.jax#L1090-L1093)
>	  これらのものは、8 ビット文字のみマッチします。新しい正規表現エンジン
>	  を使用している場合、[:lower:] と [:upper:] 以外はマルチバイト文字に
>	  も作用します。将来的にはこれらの項目は、マルチバイト文字に作用するよ
>	  うになるでしょう。

ここは

>ただし、新しい正規表現エンジンを使用している場合は [:lower:] と [:upper:] のみマルチバイト文字にも作用します。

のような感じではないでしょうか？また原文にはありませんが、二つ正規表現エンジンがあるという知識のない方がここだけ読んでも何の事だかわからなさそうなので、 `*two-engines*` タグあたりへのリンクがあると親切かなと思います。

**Comment by machakann** [comment]
ちなみに手元で試したところ  `[:graph:]` はダメですが、 `[:print:]` はマルチバイト文字にもマッチしているようですね。

**Comment by koron** [comment]
> また原文にはありませんが、二つ正規表現エンジンがあるという知識のない方がここだけ読んでも何の事だかわからなさそうなので、 *two-engines* タグあたりへのリンクがあると親切かなと思います。

これは別件として、 vim-jp/issues に原文を修正すべし、とのissueを建ててもらえると助かります。

**Comment by machakann** [comment]
ありがとうございます、建てました。

**Comment by koron** [comment]
:bow: ありがとうございます!

**Comment by machakann** [comment]
すいません、書き忘れていましたが `[:upper:]` と `[:lower:]` がマルチバイトに対応しているかはギリシャ文字 `ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩ`, `αβγδεζηθικλμνξοπρστυφχψω` で期待通りの結果だったのでそう判断しました。

**Comment by k-takata** [comment]
報告ありがとうございました。

**Comment by machakann** [comment]
ありがとうございました。
