### ISSUE TITLE
Wiki 「Vim ドキュメント翻訳者の手引き」 の些細な修正依頼

### ISSUE THREAD

**Issue by cougar-b** [vim-jp/vimdoc-ja-working#51]
Wiki ページへの pull-req の方法が分からず、Issue に登録致しました。
不適当であれば、ご指摘ください。

ページ： [Vim ドキュメント翻訳者の手引き](https://github.com/vim-jp/vimdoc-ja-working/wiki/Guide)
該当箇所：

>  *   行末の ␣> (␣は半角空白) 及び行頭の <
>    これらはサンプルを示すsyntax hightlightをかけるためのキーワードになっている。helpIgnoreグループになっているので、見落とさないように色を変えておいた方がよい。
>    ``` VIML
>    :hi Ignore ctermfg=red
>    :syn match Error /\%>79v.*/
>    ```
>  *   1行は78カラム以内
>    autofmtを入れてgqを使うとそのように整形できる。(kaoriya版には同梱)
>    (あるいは、JpFormat.vim)

指摘内容：上記説明と設定例について、 `:syn match Error /\%>79v.*/` を直後の箇条項目に含める形で、分けて記載してはいかがでしょうか。

期待する修正案：

>  *   行末の ␣> (␣は半角空白) 及び行頭の <
>    これらはサンプルを示すsyntax hightlightをかけるためのキーワードになっている。helpIgnoreグループになっているので、見落とさないように色を変えておいた方がよい。
>    ``` VIML
>    :hi Ignore ctermfg=red
>    ```
>  *   1行は78カラム以内
>    autofmtを入れてgqを使うとそのように整形できる。(kaoriya版には同梱)
>    (あるいは、JpFormat.vim)
>    ``` VIML
>    :syn match Error /\%>79v.*/
>    ```

依頼理由： コマンド例を見て `:hi Ignore ctermfg=red` の効用を推測できず、 `:syn match Error /\%>79v.*/` からコマンド例の意図をくもうとしましたが、直前の説明に関連するような効果があるとは思えず、混乱しました。
諦めて、次の箇条項目を読んで初めて、コマンド例がまとめられていることに気づき、 `helpIgnore` と `Ignore` の関係にも思い当たりました。

補足： ページの履歴確認したところ、最初から該当箇所は同様の表記で、長い間修正もないので、何らかの意図があるのかもしれません。
些細な内容で気が引けますが、上記のようなケースもあると言うことで、issue として提起致しました。
ご検討いただけたら幸いです。

**Comment by k-takata** [comment]
指摘ありがとうございます。修正しました。

**Comment by cougar-b** [comment]
ご検討、対応ありがとうございました。
