### ISSUE TITLE
popup.txt を翻訳する 

### ISSUE THREAD

**Issue by rbtnn** [vim-jp/vimdoc-ja-working#579]
とりあえずタスク作成しておきます。

**Comment by k-takata** [comment]
workingの方に移動させておきました。

**Comment by h-east** [comment]
https://github.com/vim-jp/vimdoc-ja-working/issues/207#issuecomment-497193336

**Comment by h-east** [comment]
作業中
https://github.com/vim-jp/vimdoc-ja-working/pull/588

**Comment by h-east** [comment]
Done
