### ISSUE TITLE
Note that の翻訳について

### ISSUE THREAD

**Issue by cougar-b** [vim-jp/vimdoc-ja-working#61]
現在ヘルプの翻訳では、Note that 〜 の翻訳に、シンタックスハイライトを期待した翻訳が当てられることがあるようです。
この方法について明確なルールが Wiki などで見つけられなかったため、どのような翻訳方法が望ましいのか教えて下さい。

個人的な意見としては、原文が Note: によるセクション化がされてないので特別な対応は必要ないように思いますが、原文ではハイライトがかかるので現在のような方法が取られているのだと思ってます。

ハイライト例：
![1](https://cloud.githubusercontent.com/assets/23137491/20669868/b7f8a048-b5b9-11e6-974d-58bdf095dd8d.png)

現在 change.jax において以下のような翻訳がされています。

普通に翻訳された例 :

``` diff
-	different indent than the rest.  Note that 'autoindent' must be set
+	るような段落をサポートする。'autoindent' もオンである必要がある。例: >
```

Note が翻訳文の前に補われる例 (小文字) :

``` diff
-			Note that after `:substitute` the '&' flag can't be
-			used, it's recognized as a pattern separator.
+			Note `:substitute` の後ではフラグ '&' は使えないことに
+			注意。パターンの区切り文字だと認識されてしまう。
```

NOTE が翻訳文の前に補われる例 (大文字) :

``` diff
-Note that when 'textwidth' is 0, Vim does no automatic formatting anyway (but
+NOTE 'textwidth' が 0 のとき、Vimはいかなる自動整形も行わないので注意
```

Note: (セクション) 化された例 :

``` diff
-Note that these characters may be mapped.  E.g. |%| is mapped by the matchit
-plugin.
+"- も使われる。 Note: これらの文字はマップ可能である。例: |%| は matchit プラ
+グインによってマップされている。
```

Note (セクション) 化された例 :

``` diff
-<	Note that `:s` and `:&` don't keep the flags.
+<	Note コマンド `:s` と `:&` では、前回と同じフラグは使われない。
```

**Comment by koron** [comment]
> 原文が Note: によるセクション化がされてないので特別な対応は必要ない

これに1票です。 :+1:

訳し方の候補としては `～に留意(すること|してください)`
もしくは `～に注意(すること|してください)` ですかね。

最近賢くなったGoogle 翻訳先生は「ご了承ください」って訳をくれましたがw
https://translate.google.co.jp/#en/ja/note%20that

**Comment by cougar-b** [comment]
実は、折衝案として「注意する点は、〇〇」、「注意すべきは、〇〇」のように注意を前に持ってくることも考えたのですが、なんか自然じゃないんですよね。
まー、読む人は行頭の注意がいいのかもしれませんが。

**Comment by cougar-b** [comment]
ハイライトの例を追加しました。

Koron さん、ありがとうございます。
もう少し他の方にもご意見を伺いたいです。

余り経験のない僕がここで皆さんと翻訳のルールを明確にしたいと思っているのには、以下のような理由があります：

経験がなく勝手のわからない翻訳者はルールや前例を参照、確認することが多いと思われます。
また、翻訳ガイドに載っていない（暗黙の）ルールを知るためや、表記の揺れを少なくするための事例を翻訳済みのヘルプから得ることも難しい場合がありました。

ヘルプの品質を保つため将来的に必要になる労力を考慮すると、なるべく早い段階で少々細かいところまでルールを合意、集約できていたほうが得策ではないかと考えました。

勝手な提案ですが、よろしければご協力お願いします。

**Comment by cougar-b** [comment]
この issue と関連 issue をいくつか報告させてもらって、翻訳に反映させたいなと思いつつ、なかなか手が付けられない状態が続いてしまっています。
このまま issue を放置しておくのも心苦しいので、Koron さんの提案された方向で翻訳すると言うことで、本 issue は閉じておきます。
