### ISSUE TITLE
vimdoc-ja の master への push が動いていない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/vimdoc-ja-working#653]
[Travis Build #2432](https://travis-ci.org/vim-jp/vimdoc-ja-working/builds/549706615) を最後に、vimdoc-ja の master ブランチの更新が動いていないようです。

ログは以下の通り。
[Build #2432](https://travis-ci.org/vim-jp/vimdoc-ja-working/builds/549706615):
```
$ [ "$TRAVIS_BRANCH" == "$DEPLOY_BRANCH" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && sh ./tools/deploy-master.sh _master
Cloning into '_master'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
[master 36b2578] Generated by Travis JOB 2432.1
 1 file changed, 1 insertion(+), 1 deletion(-)
To github.com:vim-jp/vimdoc-ja.git
   d68b929..36b2578  master -> master
````

[Build #2442](https://travis-ci.org/vim-jp/vimdoc-ja-working/builds/550756938):
```
$ [ "$TRAVIS_BRANCH" == "$DEPLOY_BRANCH" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && sh ./tools/deploy-master.sh _master
Cloning into '_master'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
```

**Comment by k-takata** [comment]
https://travis-ci.org/vim-jp/vimdoc-ja-working/builds/583661724
デバッグのため、`tools/deploy-master.sh` に `set -ex` を付けてみたところ、 

```
+vim -es -c helptags doc -c qall!
```

がエラーになっていることが判明。
`tools/deploy-gh-pages.sh` のログを見ると、

```
Vim(helptags):E154: Duplicate tag "E996" in file ./popup.jax
```

が表示されていることから、`E996` が重複しているのが原因と推測される。
#644 をマージすれば解決か？（ただしマージの際には https://github.com/vim-jp/vimdoc-ja-working/pull/644#issuecomment-525097147 に留意。）

**Comment by k-takata** [comment]
`vim -es -c "helptags doc" -c "qall!"` がエラーになったときに、エラーメッセージが表示されるようになっていると分かりやすいと思いますが、何か方法ありますかね？

**Comment by h-east** [comment]
#654 のmergeで無事 vimdoc-ja の master へ pushされたようです。

**Comment by h-east** [comment]
あれ？さっきmergeしたpopup.jaxが降ってこない。。

**Comment by h-east** [comment]
> あれ？さっきmergeしたpopup.jaxが降ってこない。。

E154: Duplicate tag "globpath()" in file doc/eval.jax

**Comment by k-takata** [comment]
タグの重複、PRのCIでも検出できるようになってると便利ですね。

**Comment by h-east** [comment]
> E154: Duplicate tag "globpath()" in file doc/eval.jax

vim-jp/vimdoc-ja-working/pull/682 で直りました。

> タグの重複、PRのCIでも検出できるようになってると便利ですね。

ですね。

**Comment by k-takata** [comment]
#683 でできそう。（ワンライナーではできなかった。）
