### ISSUE TITLE
vimdoc help の HTML 変換処理部分のライセンスと利用

### ISSUE THREAD

**Issue by tsuyoshicho** [vim-jp/vimdoc-ja-working#733]
## 変換
現在、 vimdoc-jpでは https://vim-jp.org/vimdoc-ja/ でHTMLで公開するようにしており、その生成をtools以下にあるファイル群で実施していますね
(コアな処理はTOhtml / 2html.vim )

## ライセンス
この部分のライセンスについて確認をしたくIssueを上げました
現状どのようになっているでしょうか?

## 理由
2019 Adventカレンダーネタとして、この部分を流用したものを作成する(もうしてしまった、ですが...)ので、あらためてライセンス的な問題がないか確認したく。

1. ライセンスがある(あるいは制定する)
   上記のツールはそのライセンスに準拠させます
2. ライセンスがない(あるいは決めるつもりはない、流用などなし)
  a. 上記ツールの非公開
  b. 上記ツールをvim-jpへ寄贈(有用と思っていただけたのなら、うれしくないかもしれませんが...)
  どちらでもアリだと思いますので、相談させてください。

URL
[tsuyoshicho/action\-vimhelp\-html\-generate: Generate html from Vim help \(/doc\)](https://github.com/tsuyoshicho/action-vimhelp-html-generate)

**Comment by k-takata** [comment]
現時点ではツールのライセンスは明確にはなっていないですね。

一番のメインの部分である makehtml.vim と buildhtml.vim を最初に作ったのは @ynkdir さんです。
@ynkdir さんは最近ほとんど活動されていませんが、ライセンスの指定等ありますか？（ynkdirさんの作ったものはPublic DomainかVim Licenseが多い印象がありますが。）
他にツールの開発にかかわった人は、@koron さん、私、他数人でしょうか。

個人的には、Vim関連のツールということで、Vim Licenseが無難かなと思っています。PDでも構いませんが。
いずれにしても、本ツールを流用することに問題があると考えている人はいないと思います。（異存がある人は表明してください。）

（そう言えば翻訳の成果物のライセンスってどうなってましたっけ？）

**Comment by ynkdir** [comment]
すみませんご無沙汰しております。
私が書いたものは好きに使ってください。
一切を譲渡、放棄、あるいは容認します。

**Comment by tsuyoshicho** [comment]
了解です。その旨をリポジトリに記載します。
ライセンスは現状MITにしてるけど、理念を考えるとCC0かな...(拘りはないので)

**Comment by tsuyoshicho** [comment]
更新しました。

Issueとしては一旦クローズしてよいと思いますので、クローズします。
正式なライセンスの検討などの時に再Openとか別にやる+リンクなどしていただければと思います。
