### ISSUE TITLE
textprop.jax の文体が混ざっている

### ISSUE THREAD

**Issue by k-takata** [vim-jp/vimdoc-ja-working#812]
当初 textprop.jax は敬体で書かれていたが、常体で書かれていた eval.jax から関数の説明を移動してきたために、文体が混ざってしまった。
https://github.com/vim-jp/vimdoc-ja-working/pull/811#issuecomment-613176214

常体に統一するのが良いかもしれない。

**Comment by k-takata** [comment]
terminal.jax も同様。

**Comment by tsuyoshicho** [comment]
index.jax 機能リストの項目の説明で記法がまざっている #816

index.jax の項目リストにも似た傾向あり(原文がそうかもしれないが)
issueが重複気味なので、コメント後closeします。

**Comment by h-east** [comment]
index.jaxの件は当該issueをreopenしました。
ですので、このissueは対応完了ということでcloseします。
