### ISSUE TITLE
日本語環境だと翻訳されるメッセージの表記方法が統一されていない

### ISSUE THREAD

**Issue by obcat** [vim-jp/vimdoc-ja-working#899]
# 問題の内容

#896, #898 からです。
`:language ja_JP` だと一部のメッセージが日本語に翻訳されますが、そのようなメッセージの表記方法がヘルプ全体で統一されていません。

たとえば、`*'shortmess'*` では、そのようなメッセージはヘルプの本文中で日本語に訳されています（`[最終行が不完全]`, `[変更あり]` など）：

https://github.com/vim-jp/vimdoc-ja-working/blob/ea36c8dd84dedf1a55c8f8a0720bcc0b1ee454d7/doc/options.jax#L6773-L6787

一方で、`*read-messages*` では、本文中では原文ママで、日本語訳は訳注で記載されています。

https://github.com/vim-jp/vimdoc-ja-working/blob/ea36c8dd84dedf1a55c8f8a0720bcc0b1ee454d7/doc/insert.jax#L1952-L1982

一貫性のため、このようなメッセージの表記方法を全体で統一したほうがよいと思います。

# 表記方法の候補

表記方法の候補としては次の４つになるかと思います。

1. 本文中で日本語に翻訳、訳注はなし。（`*'shortmess'*` での表記方法と同じ）

2. 本文中で日本語に翻訳、原文を訳注で記載する。

3. 本文中では原文ママ。日本語訳を訳注で記載する。（`*read-messages*` での表記方法と同じ）

4. 本文中では原文ママ。訳注もなし。

個人的には 3 が良いような気がしますが、どうでしょうか？

**Comment by Milly** [comment]
3 がよいと思います。

**Comment by obcat** [comment]
vim-jp slack で Milly さんに起票していただいた poll の途中結果を載せておきます。

<img width="600" alt="ss 2021-03-27 20 06 36" src="https://user-images.githubusercontent.com/64692680/112718717-295f8b00-8f38-11eb-8aa9-32c9c1a29047.png">

https://vim-jp.slack.com/archives/CJMV3MSLR/p1616677702147100


`Sat Mar 27 20:06:36 JST 2021` 時点で、画像の通り

1. `0` 票
1. `0` 票
1. `8` 票
1. `0` 票

となっています。

表記方法を統一する方針をとるのであれば、3 に決定しても良いかなと思いますが、いかがでしょうか？
それと今思いましたが、「あえて表記方法を統一しない」という選択肢も入れておいたほうがよかったですね・・

**Comment by tsuyoshicho** [comment]
ここで仮で3方向で修正をつくっておき、対応可能にする、くらいがいいですかね

**Comment by h-east** [comment]
3 に1票。
(私は普段 `:lang message C` を設定しているので、"原文ママ+訳注" が良いですね)

**Comment by obcat** [comment]
みなさんありがとうございます。では、`3. 原文ママ+訳注` で決定ということでよさそうですね。

[wiki/Guide#vim-ドキュメント翻訳者の手引き](https://github.com/vim-jp/vimdoc-ja-working/wiki/Guide#vim-%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E7%BF%BB%E8%A8%B3%E8%80%85%E3%81%AE%E6%89%8B%E5%BC%95%E3%81%8D) に記載する用の文章を書いてみましたが、こんな感じでどうでしょうか？
これでよければ、どなたか権限のある方に記載していただければと思います。

**整形前（コピペ用）**

https://gist.githubusercontent.com/obcat/0067b35cb161b7f4b849016f0499ca14/raw/9a3b52b013aa781a05ffc20f7f72063ff7838250/vimdoc-ja_writing_manual_japanese%2520messages.md

**整形後**

- 日本語環境だと翻訳されるメッセージ
  `:language messages ja_JP` などの日本語環境では、一部のメッセージが日本語に翻訳される。そのようなメッセージは**本文中では原文のままにし、その日本語訳を訳注で記載する**こと。基本的に一つのメッセージに対して一つの訳注をつければよいが、くどくなる場合は複数のメッセージに対して一つの訳注をつけてもよい。例：
  
  `1` 訳注 / `1` メッセージ
  ```
  	h F   ヘルプバッファフラグ。表示されるのは "[help]"。
  	      {訳注: 日本語メッセージの場合: "[ヘルプ]"}
  	H F   ヘルプバッファフラグ。表示されるのは ",HLP"。
  	w F   プレビューウィンドウフラグ。表示されるのは "[Preview]"。
  	      {訳注: 日本語メッセージの場合: "[プレビュー]"}
  ```

  `1` 訳注 / `n` メッセージ（`n >= 2`）
  ```
   							*read-messages* 
   ファイルを読み込むときVimはその情報を表示する。いくつかのものについての説明 
   をあげる。他のものは見ればわかる。ロングとショートのどちらを使うかは 
   'shortmess' オプションに依存する。 
    
   	ロング		ショート	意味 ~ 
   	[readonly]	{RO}		ファイルは書き込み制限されている 
   	[fifo/socket]			ストリームを使っている 
   	[fifo]				FIFOストリームを使っている 
   	[socket]			ソケットストリームを使っている 
   	[CR missing]			"dos" ファイルフォーマットで読み込ん 
   					でいてCRのないNLを見つけた 
   	[NL found]			"mac" ファイルフォーマットで読み込ん 
   					でいてNLを見つけた(unixフォーマット 
   					なのだろう) 
   	[long lines split]		少なくとも1つの行が2つに分割された 
   	[NOT converted]			'fileencoding' から 'encoding' の変換 
   					が失敗した 
   	[converted]			'fileencoding' から 'encoding' の変換 
   					を実施した 
   	[crypted]			暗号が解除された 
     	[READ ERRORS]			ファイルを全て読み込めなかった 
  
   {訳注: 以下日本語メッセージの場合: 
   	ロング		ショート	意味 ~ 
   	[読込専用]	[読専]		ファイルは書き込み制限されている 
   	[FIFO/ソケット]			ストリームを使っている 
   	[FIFO]				FIFOストリームを使っている 
   	[ソケット]			ソケットストリームを使っている 
   	[CR無]				"dos" ファイルフォーマットで読み込ん 
   					でいてCRのないNLを見つけた 
  ```

**Comment by uakms** [comment]
{訳注:} 部分が離れてしまう場合は、次のように微妙な文言の違いに気づきにくいですね。
```
	[READ ERRORS]			ファイルを全て読み込めなかった
	[読込エラー]			ファイルを全ては読み込めなかった
```

**Comment by h-east** [comment]
@obcat 
> どなたか権限のある方に記載していただければと思います。

obcatさんをvimdoc-jaメンバに招待しました。
様子を見て`手引き`を更新しても良いと思います。

**Comment by h-east** [comment]
@uakms これ、同じ訳にしてしまっても良いんじゃないでしょうか？
(敢えて違う訳にしている理由があるのかな)

**Comment by obcat** [comment]
> {訳注:} 部分が離れてしまう場合は、次のように微妙な文言の違いに気づきにくいですね。
> ```
> 	[READ ERRORS]			ファイルを全て読み込めなかった
> 	[読込エラー]			ファイルを全ては読み込めなかった
> ```

これ、前者は誤訳だと思うので他のちょっとした修正と合わせて PR 出しておきました。#900
複数に一つの訳注を付ける場合、おっしゃるとおり訳注が離れてしまうので、原文と日本語訳の対応が明確になるように工夫する必要がありますね。

> obcatさんをvimdoc-jaメンバに招待しました。
> 様子を見て手引きを更新しても良いと思います。

ありがとうございます！join しました。
手引きについても了解しました。

**Comment by obcat** [comment]
とりあえず上記のまま手引に記載してみました。改善点があったら修正していただければと思います。

この issue の目的は達成したので close します。みなさんありがとうございました！
