### ISSUE TITLE
"Vim ドキュメント翻訳者の手引き" を改善したい

### ISSUE THREAD

**Issue by obcat** [vim-jp/vimdoc-ja-working#935]
## Problem

Wiki の [Vim ドキュメント翻訳者の手引き](https://github.com/vim-jp/vimdoc-ja-working/wiki/Guide) が少し見づらいと感じます。

## Suggestion

とりあえず次のような改善を加えて体裁を整えたいです。

- 適切に見出し (`#`、`##`、...) を追加する
- 意見やコメント部分を本文と差別化する
- 適切な例を追加する

特に見出しがあると特定の部分をリンクで参照しやすくなるので良いんじゃないかなと思います。

よろしければ私がやろうかなと思っているのですが、更新してもいいでしょうか?
Wiki には PR できないみたいなので、直接更新してからここに事後報告するという形になるとは思いますが…

**Comment by tsuyoshicho** [comment]
一度体裁改訂版をここに例示して、調整してもいいかもですね

**Comment by obcat** [comment]
ありがとうございます。そうですね。
一応こんな感じにしようかなと考えています (実はモチベがあるうちにと思ってもうローカルでやり始めています 😇)

# Vim ドキュメント翻訳者の手引き

## はじめに

公式ヘルプの以下の場所にヘルプの書き方が記載されている。参照すること。

- `:h help-writing`

  (翻訳ヘルプに限らない一般的な) ヘルプの書式について。

- `:h help-translated`

  翻訳ヘルプを作成する際の注意事項。


## 文体

ユーザーマニュアルでは敬体 (ですます調) を用いる。

リファレンスマニュアルでは敬体と常体 (だである調) のどちらを用いても構わない。現状では両方が混在している。少なくとも、1 つのファイルではどちらかに統一しておきたい。

敬体を用いる場合でも、以下の場所では常体を用いること。

- 見出し

  ```help
  プラグインを使う
  ----------------
  
  まず、プラグイン自身のドキュメントを読んで、動作条件を確認してください。
  ```

- 短い箇条書き

  ```help
  プラグインの追加は以下の手順で行います:
  1. プラグインを入手する
  2. 正しいディレクトリにコピーする
  ```

- サンプルコードのコメント

  ```help
  :smile					*:smile*
      ユーザーを幸せにします。例: >
        " 10000 回幸せにする
        for i in range(10000)
          smile
        endfor
  ```


### 命令形の翻訳

リファレンスマニュアルなので、命令しているというよりは操作の手順を簡潔に述べているだけであって、特に命令形だからという意識はしなくて良い。

...

**Comment by obcat** [comment]
何の了承も得てませんが勝手に更新しました 😇

diff: https://github.com/vim-jp/vimdoc-ja-working/wiki/Guide/_compare/3ddfd3a%5E...3ddfd3a

主に体裁を整えただけです。ちょっとメモを追加したり文章に手を加えたりはしましたが、項目を消したりはしてませんし内容としては変わってないはずです。

何かまずい点があったら教えて下さい 🙇  revert します…

**Comment by k-takata** [comment]
半角空白を明示する部分で `␣` を使っていたところを `_` に変更しているようですが、何か理由ありますか？

**Comment by obcat** [comment]
> 半角空白を明示する部分で ␣ を使っていたところを _ に変更しているようですが、何か理由ありますか？

たしか変更したきっかけは文章を書き直すときに `␣` をコピペするのが手間だったからだと記憶しています。で「`_` のほうが見た目がすっきりしていて見やすいな」と思ったのでそのままにしました。
`␣` のままにしておいたほうがよかったでしょうか…?

**Comment by k-takata** [comment]
`␣` は空白を表すための記号なので、元の文を書いたときはわざわざこの記号を使いました。
`_` だと半角空白の代わりに使っているのか本当の `_` なのかが注釈を読まないと分からないのがよくないと思います。

**Comment by obcat** [comment]
> `␣` は空白を表すための記号

あー、それは知らなかったです… 注釈の必要性に関してはどちらも同じだと思っていました (知らなかったので…)
`␣` に戻しておきます🙇

**Comment by k-takata** [comment]
参考: https://ja.wikipedia.org/wiki/%E7%A9%BA%E7%99%BD%E8%A8%98%E5%8F%B7

**Comment by obcat** [comment]
ありがとうございます。よく考えたら `_` だとスペースが 2 個以上連続する場合に文字どうしが繋がったように見えてしまって分かりづらくなりますね。`␣` にセリフっぽいものが付いているのはそうならないようにするためか。勉強になりました。

**Comment by obcat** [comment]
行頭の `<` に関する、このような記述を加えたいと思っています:

https://github.com/obcat/vimdoc-ja-working-wiki/pull/1/files?short_path=5bc1003#diff-5bc100391353e4f66f1ca7eaec6e2d91519cd440a68bbfc0f04b74f3293b0655

こちらのルール:

> ただしコードブロックの後ろが空行の場合は、そこに < を追加する:

を追加することが目的です。いかがでしょうか?

**Comment by obcat** [comment]
上記の新ルール:

> ただしコードブロックの後ろが空行の場合は、そこに < を追加する:

ですが、やっぱり微妙な気がしてきたので、この部分の提案は取り下げます。

理由: 原文に更新があって `<` 始まりでなくなったとき、余計な `<` を消す必要がありますが、`<` を空行、つまり更新箇所と別の行に追加していた場合、`<` の存在に気づけず消し忘れる可能性あります。一方で二重 (`<<`) になっていれば存在に気づきやすいので消し忘れる可能性は低いんじゃないかな、と思ったからです。

その他の変更 (例の追加など) は有用だと思うので、適用してもいいかなと思っています。
ちょっと手を加えてこんな感じになりました:

https://github.com/obcat/vimdoc-ja-working-wiki/pull/1/files?short_path=5bc1003#diff-5bc100391353e4f66f1ca7eaec6e2d91519cd440a68bbfc0f04b74f3293b0655

- 空行がある場合の新ルールを削除しました。
- 空行がある場合も `<` を二重にすることと、その理由 (上記のもの) を追記しました。

何か意見がありましたら教えてください。

**Comment by tsuyoshicho** [comment]
文言などにはあるかと思いますが、(改変の度合いは上りますが)記法としては自然なので、できれば採用されればなあと思います。
