### ISSUE TITLE
vimdoc-jaの更新方法をPersonal Access TokenからDeploy Keyに切り替える

### ISSUE THREAD

**Issue by koron** [vim-jp/vimdoc-ja-working#991]
https://github.com/vim-jp/vimdoc-ja-working/pull/901 において
GitHub Actionsに移行する際に vimdoc-ja の更新方法が PATに切り替わったようです。

PATはそれを発行した人がアクセス可能なレポジトリすべてに効力を及ぼします。
もしも @k-takata さんが発行したのであれば、k-takataさんが持つすべてのレポジトリを
vimdoc-ja-working のGitHub Actionsが潜在的に書き換えられることを意味します。

仮に k-takata さんが vim/vim などに変更権限をもっていれば
それらがすべてvimdoc-ja-workingから変更できるという意味です。

これは非常によろしくない状態ですので
Deploy Keys を使って vimdoc-ja しか書き換えられない状態に是正したいです。

---

参考資料:  [Zolaで作ったサイトをGitHub ActionsでGitHub PagesにDeployする](https://zenn.dev/block/articles/ba618e3dc90f7aff97ba)

**Comment by koron** [comment]
安全側に倒すという意味で、secretsから現在のPATを消すことで
vimdoc-ja への自動デプロイを止めます。

申し訳ないですが緊急避難措置としてご理解ください。

復帰はDeploy Keyに変更したら、を予定しています。

cc: @h-east

**Comment by koron** [comment]
今消しました。

**Comment by koron** [comment]
@thinca さんが slacklog と同じ形式に設定してくれる予定。

**Comment by koron** [comment]
commentにclose入ってたからマージで閉じちゃったけど
実際に更新されるのを確認してから閉じたいので、
いったんreopenします。

**Comment by koron** [comment]
Actionsは動いたが検証は不完全
https://github.com/vim-jp/vimdoc-ja-working/runs/4544839107?check_suite_focus=true

見てみるとpullはできてるが
変更がないためかpushはしてない(しっぱいもしてない)

なので何かしら変更を入れ、それがvimdoc-jaに入ったことが確認できるまではこのまま。

**Comment by koron** [comment]
ここで vimdoc-ja に変更が入ったかは確認できる。

https://github.com/vim-jp/vimdoc-ja/commits/master
https://github.com/vim-jp/vimdoc-ja/commits/gh-pages

**Comment by tsuyoshicho** [comment]
合せてコメントとして連絡
@k-takata  さん、お手数かけますが、PAT自体のrevokeもよろしくおねがいします。(他では使ってないだろうとは思うので)

**Comment by koron** [comment]
https://github.com/vim-jp/vimdoc-ja-working/pull/996

**Comment by tsuyoshicho** [comment]
上記PRのマージで
https://github.com/vim-jp/vimdoc-ja/commit/e63e1202cb6e2791da4767d429dd03dc1fe862d3
https://github.com/vim-jp/vimdoc-ja/commit/05282dff47931cc180fcc85bd2d42099a5c3fdd9
として、それぞれコミットが入りました。

適切にデプロイできたことが確認できたと思います。

**Comment by koron** [comment]
to all

Deploy Key への切り替えと、それがうまく機能したことが確認できました。
よって本件はcloseいたします。

ご協力ありがとうございました!
